import Vue from 'vue'
import Vuex from 'vuex'

Vue.use(Vuex)

//存放购物车数据的全局变量，以保证在反复跳转后，订单信息不会丢失
//Vue.prototype.$cart = [];

export default new Vuex.Store({
  state: {
    cart: new Map(),
    username:"user1",
    address:"我是收货地址",
    productDict: new Map([  //产品的信息表
      ['4-AB',"BISAGRA 4''"],
      ['4-AC',"BISAGRA 4''"],
      ['4-SN',"BISAGRA 4''"],

      [ 'CLIC-1', 'SUJETADOR'],
              ['SUJ-1',  'SUJETADOR'],
              ['SUJ-2',  'SUJETADOR'],
              ['SUJ-3',  'SUJETADOR'],

              ['TORNILLO A',  'TORNILLO'],
              ['TORNILLO N',  'TORNILLO'],
              ['TORNILLO T2',  'TORNILLO'],
              ['TORNILLO T2-1',  'TORNILLO'],
              ['TORNILLO A-1000',  'TORNILLO'],
             ['T2-T',  'TORNILLO'],
             ['T2-TB',  'TORNILLO']    ,
             ['T2-TB-L',  'TORNILLO'],
             ['T2-TC-L',  'TORNILLO'] ,
             ['T2-T-L',  'TORNILLO'] ,   

            [ 'High Grab-118',  'SILICONA'] ,
             ['High Grab-116', 'SILICONA']  ,
              ['HT-N',  'SILICONA']  ,
               ['HT-C',  'SILICONA'] ,

              ['OMEGA-3 (0,45)',  'OMEGA'] ,

             ['ANGULO-3 (0,45)',  'ANGULO'] ,
              ['ANGULO-3 (35-0.45)',  'ANGULO' ]  ,
               ['CONERBEAD-3 (0,45)',  'ANGULO'] ,

              [ 'MONTANTE-3 (0,45)',  'MONTANTE'] ,
               ['MONTANTE-3 (0,35)',  'MONTANTE'] ,
              ['MONTANTE-64',  'MONTANTE']  ,
              ['MONTANTE-70',  'MONTANTE']  ,
               ['MONTANTE-64 SS',  'MONTANTE'] ,

              ['PAT-1200',   'PERFILERIA ACUSTICA TRANSVERSAL1.2'],
            [ 'PAT-600',   'PERFILERIA ACUSTICA TRANSVERSAL0.6'] ,
            [ 'PAP-3000',   'PERFILERIA ACUSTICA PERIMETRAL' ],  

          ['PAC-3600',  'CENTRAL ACOUSTIC PROFILERY']  ,
           [ 'PAC-3600N',  'CENTRAL ACOUSTIC PROFILERY']     ,

          [ 'SOLERA-65',  'SOLERA'] ,
           [ 'SOLERA-72',  'SOLERA']    ,
            [ 'SOLERA-3 (0,45)',  'SOLERA']    ,
             [ 'SOLERA-3 (0,35)',  'SOLERA']   ,

            [ 'Buña Z-2,4m(0,4)', 'Buña Z']  ,

            [ 'PF01C', '1PF01'],
                [ 'PF02', '1PF02'],
                [ 'PF02C', '1PF02'],
                [ 'PF03', '1PF03'],
                [ 'PF03C', '1PF03'],
                [ 'PF04', '1PF04'],
                [ 'PF04C', '1PF04'],
                [ 'PF05', '1PF05'],
                [ 'PF05C', '1PF05'],
                [ 'PF06C', '1PF06'],
                [ 'PF07C', '1PF07'],
                [ 'PF08C', '1PF08'],
                [ 'PF09C', '1PF09'],
                [ 'PF09 SPC', '1PF09'],
                [ 'PF10', '1PF10'],
                [ 'PF10C', '1PF10'],
                [ 'PF11C', 'images/TBD1'],
                [ 'PF11 SPC', 'images/TBD1'],
                [ 'PF12C', '1PF12'],
                [ 'PF12 SPC', '1PF12'],
                [ 'PF13', '1PF13'],
                [ 'PF14', '1PF14'],
                [ 'PF15', '1PF15'],
                [ 'PF16', 'images/TBD1'],
                [ 'PF17', 'images/TBD1'],
                [ 'PF18', 'images/TBD1'],
                [ 'PF19', '1PF19'],
                [ 'PF20', 'images/TBD1'],
                [ 'PF21', '1PF21'],
                [ 'PF22', 'images/TBD1'],
                [ 'PF23', '1PF23'],

                { name: 'AP-1', image: 'images/TBD1.jpg' },
                { name: 'AP-2', image: 'images/TBD1.jpg' },
                { name: 'AP-3', image: 'images/TBD1.jpg' },
                { name: 'AP-4', image: 'images/TBD1.jpg' },
                { name: 'AP-5', image: 'images/TBD1.jpg' },

                { name: 'M-1209', image: 'images/TBD1.jpg' },
                { name: 'M-1212', image: 'images/TBD1.jpg' },
                { name: 'M-8123', image: 'images/TBD1.jpg' },
                { name: 'M-8129', image: 'images/TBD1.jpg' },
                { name: 'M-8806', image: 'images/TBD1.jpg' },
                { name: 'M-8809', image: 'images/TBD1.jpg' },

                { name: 'GS-154', image: 'images/CIELO-MODULAR/GS-154.png' },
                { name: 'GS-238', image: 'images/CIELO-MODULAR/GS-238.png' },
                { name: 'GS-975', image: 'images/CIELO-MODULAR/GS-975.png' },
                { name: 'GS-996', image: 'images/CIELO-MODULAR/GS-996.png' },
                { name: 'GS-2034-1', image: 'images/TBD1.jpg' },
                { name: 'GS-2034-2', image: 'images/TBD1.jpg' },

                { name: 'BV595-0', image: 'images/CIELO-MODULAR/BV595-0.jpg' },
                { name: 'BV595-1', image: 'images/CIELO-MODULAR/BV595-1.jpg' },
                { name: 'BV595-2', image: 'images/CIELO-MODULAR/BV595-2.jpg' },
                { name: 'BV595-3', image: 'images/CIELO-MODULAR/BV595-3.jpg' },
                { name: 'BV595-4', image: 'images/CIELO-MODULAR/BV595-4.jpg' },
                { name: 'BV595-5', image: 'images/CIELO-MODULAR/BV595-5.jpg' },
                { name: 'BV595-6', image: 'images/CIELO-MODULAR/BV595-6.jpg' },
                { name: 'BV595-7', image: 'images/CIELO-MODULAR/BV595-7.jpg' },
                { name: 'BV595-8', image: 'images/CIELO-MODULAR/BV595-8.jpg' },
                { name: 'BV595-9', image: 'images/CIELO-MODULAR/BV595-9.jpg' },
                { name: 'BV595-10', image: 'images/CIELO-MODULAR/BV595-10.jpg' },
                { name: 'BV595-11', image: 'images/CIELO-MODULAR/BV595-11.jpg' },
                { name: 'BV595-12', image: 'images/CIELO-MODULAR/BV595-12.jpg' },
                { name: 'BV595-13', image: 'images/CIELO-MODULAR/BV595-13.jpg' },

                { name: 'BV200-B', image: 'images/CIELO-FALSO-PVC/BV200-B.jpg' },
                { name: 'BV200-B10', image: 'images/CIELO-FALSO-PVC/BV200-B10.jpg' },
                { name: 'BV200-E10', image: 'images/TBD1.jpg' },

                { name: 'BV202-25', image: 'images/CIELO-FALSO-PVC/BV202-25.jpg' },
                { name: 'BV250-B1', image: 'images/CIELO-FALSO-PVC/BV250.jpg' },
                { name: 'BV250-B2', image: 'images/CIELO-FALSO-PVC/BV250.jpg' },
                { name: 'BV250-M2', image: 'images/CIELO-FALSO-PVC/BV250-M2.jpg' },
                { name: 'BV2500', image: 'images/TBD1.jpg' },
                { name: 'BV2501', image: 'images/CIELO-FALSO-PVC/BV2501.png' },
                { name: 'BV2502', image: 'images/CIELO-FALSO-PVC/BV2502.jpg' },
                { name: 'BV2503', image: 'images/CIELO-FALSO-PVC/BV2503.jpg' },
                { name: 'BV2504', image: 'images/CIELO-FALSO-PVC/BV2504.jpg' },
                { name: 'BV2505', image: 'images/CIELO-FALSO-PVC/BV2505.png' },
                { name: 'BV2506', image: 'images/CIELO-FALSO-PVC/BV2506.png' },
                { name: 'BV251', image: 'images/CIELO-FALSO-PVC/BV251.jpg' },
                { name: 'BV2510', image: 'images/CIELO-FALSO-PVC/BV2510.jpg' },
                { name: 'BV2512', image: 'images/CIELO-FALSO-PVC/BV2512.jpg' },
                { name: 'BV2513', image: 'images/CIELO-FALSO-PVC/BV2513.jpg' },
                { name: 'BV2514', image: 'images/CIELO-FALSO-PVC/BV2514.jpg' },
                { name: 'BV2515', image: 'images/TBD1.jpg' },
                { name: 'BV2517', image: 'images/TBD1.jpg' },
                { name: 'BV252', image: 'images/CIELO-FALSO-PVC/BV252.jpg' },
                { name: 'BV2522', image: 'images/CIELO-FALSO-PVC/BV2522.jpg' }, 
                { name: 'BV2522-6', image: 'images/CIELO-FALSO-PVC/BV2522.jpg' },              
                { name: 'BV2524', image: 'images/CIELO-FALSO-PVC/BV2524.jpg' },                
                { name: 'BV2525', image: 'images/CIELO-FALSO-PVC/BV2525.jpg' },
                { name: 'BV2526', image: 'images/CIELO-FALSO-PVC/BV2526.jpg' },
                { name: 'BV2527', image: 'images/TBD1.jpg' },
                { name: 'BV2528', image: 'images/TBD1.jpg' },
                { name: 'BV2529', image: 'images/TBD1.jpg' },
                { name: 'BV253', image: 'images/CIELO-FALSO-PVC/BV253.jpg' },
                { name: 'BV253-5M', image: 'images/CIELO-FALSO-PVC/BV253.jpg' },
                { name: 'BV253-H', image: 'images/CIELO-FALSO-PVC/BV253.jpg' },
                { name: 'BV2531', image: 'images/TBD1.jpg' },
                { name: 'BV2531-6', image: 'images/TBD1.jpg' },
                { name: 'BV2532', image: 'images/TBD1.jpg' },
                { name: 'BV2536', image: 'images/CIELO-FALSO-PVC/BV2536.jpg' },
                { name: 'BV2538', image: 'images/TBD1.jpg' },
                { name: 'BV254', image: 'images/CIELO-FALSO-PVC/BV254.jpg' },
                { name: 'BV254-A', image: 'images/CIELO-FALSO-PVC/BV254.jpg' },
                { name: 'BV254-H', image: 'images/CIELO-FALSO-PVC/BV254.jpg' },
                { name: 'BV2541', image: 'images/TBD1.jpg' },
                { name: 'BV2543', image: 'images/TBD1.jpg' },
                { name: 'BV2545', image: 'images/CIELO-FALSO-PVC/BV2545.jpg' },
                { name: 'BV2548', image: 'images/TBD1.jpg' },
                { name: 'BV2548-6', image: 'images/TBD1.jpg' },
                { name: 'BV255', image: 'images/CIELO-FALSO-PVC/BV255.jpg' },
                { name: 'BV255-A', image: 'images/CIELO-FALSO-PVC/BV255.jpg' },
                { name: 'BV255-H', image: 'images/CIELO-FALSO-PVC/BV255.jpg' },
                { name: 'BV2550', image: 'images/TBD1.jpg' },
                { name: 'BV2553', image: 'images/TBD1.jpg' },
                { name: 'BV2555', image: 'images/TBD1.jpg' },
                { name: 'BV2557', image: 'images/TBD1.jpg' },
                { name: 'BV2557-H', image: 'images/TBD1.jpg' },
                { name: 'BV2557N-W', image: 'images/TBD1.jpg' },
                { name: 'BV2557N-W-H', image: 'images/TBD1.jpg' },
                { name: 'BV2559', image: 'images/CIELO-FALSO-PVC/BV2559.jpg' },
                { name: 'BV256', image: 'images/CIELO-FALSO-PVC/BV256.jpg' },
                { name: 'BV2560', image: 'images/CIELO-FALSO-PVC/BV2560.jpg' },
                { name: 'BV2561', image: 'images/CIELO-FALSO-PVC/BV2561.png' },
                { name: 'BV2562', image: 'images/CIELO-FALSO-PVC/BV2562.jpg' },
                { name: 'BV2563', image: 'images/CIELO-FALSO-PVC/BV2563.jpg' },
                { name: 'BV2564', image: 'images/TBD1.jpg' },
                { name: 'BV2565', image: 'images/TBD1.jpg' },
                { name: 'BV2567', image: 'images/TBD1.jpg' },
                { name: 'BV257', image: 'images/TBD1.jpg' },
                { name: 'BV2570', image: 'images/TBD1.jpg' },
                { name: 'BV2571', image: 'images/TBD1.jpg' },
                { name: 'BV2572', image: 'images/CIELO-FALSO-PVC/BV2572.jpg' },
                { name: 'BV2573-H', image: 'images/TBD1.jpg' },
                { name: 'BV258', image: 'images/CIELO-FALSO-PVC/BV258.jpg' },
                { name: 'BV259', image: 'images/CIELO-FALSO-PVC/BV259.jpg' },
                { name: 'BV2590-H', image: 'images/TBD1.jpg' },
                { name: 'BV2592', image: 'images/TBD1.jpg' },
                { name: 'BV2592-A', image: 'images/TBD1.jpg' },
                { name: 'BV2592-H', image: 'images/TBD1.jpg' },
                { name: 'BV2593', image: 'images/TBD1.jpg' },
                { name: 'BV2593-H', image: 'images/TBD1.jpg' },
                { name: 'BV2594', image: 'images/TBD1.jpg' },
                { name: 'BV2595', image: 'images/TBD1.jpg' },
                { name: 'BV2595-A', image: 'images/TBD1.jpg' },
                { name: 'BV2595-H', image: 'images/TBD1.jpg' },
                { name: 'BV2598-H', image: 'images/TBD1.jpg' },
                { name: 'BV2599', image: 'images/TBD1.jpg' },

                { name: 'BV300', image: 'images/CIELO-FALSO-PVC/BV258.jpg' },
                { name: 'BV300-B', image: 'images/CIELO-FALSO-PVC/BV300.jpg' },
                { name: 'BV301', image: 'images/CIELO-FALSO-PVC/BV301.jpg' },
                { name: 'BV303', image: 'images/TBD1.jpg' },
                { name: 'BV350', image: 'images/TBD1.jpg' },
                { name: 'BV351', image: 'images/TBD1.jpg' },
                { name: 'BV352', image: 'images/TBD1.jpg' },
                { name: 'BV353', image: 'images/TBD1.jpg' },
                { name: 'BV354', image: 'images/CIELO-FALSO-PVC/BV354.jpg' },
                { name: 'BV354-H', image: 'images/CIELO-FALSO-PVC/BV354.jpg' },
                { name: 'BV355', image: 'images/CIELO-FALSO-PVC/BV355.jpg' },
                { name: 'BV355-H', image: 'images/CIELO-FALSO-PVC/BV355.jpg' },
                { name: 'PB300-B', image: 'images/TBD1.jpg' },
                { name: 'PB300M', image: 'images/TBD1.jpg' },
                { name: 'PB301', image: 'images/TBD1.jpg' },
                { name: 'PB302', image: 'images/TBD1.jpg' },
                { name: 'PB303', image: 'images/TBD1.jpg' },
                { name: 'PB305', image: 'images/TBD1.jpg' },

                { name: 'T01', image: 'images/CORNISA/T01.png' },
                { name: 'T01 MATE', image: 'images/CORNISA/T01-MATE.png' },
                { name: 'T01-C', image: 'images/TBD1.jpg' },
                { name: 'T01-K', image: 'images/TBD1.jpg' },
                { name: 'T01-M', image: 'images/CORNISA/T01-M.png' },
                { name: 'T01-PL', image: 'images/CORNISA/T01-PL.png' },
                { name: 'T10', image: 'images/TBD1.jpg' },
                { name: 'T-205T', image: 'images/TBD1.jpg' },
                { name: 'T-207T', image: 'images/TBD1.jpg' },
                { name: 'T-208T', image: 'images/TBD1.jpg' },
                { name: 'T25-07', image: 'images/TBD1.jpg' },
                { name: 'T-251', image: 'images/TBD1.jpg' },
                { name: 'T-251-A', image: 'images/TBD1.jpg' },
                { name: 'T-253', image: 'images/TBD1.jpg' },
                { name: 'T-253-H', image: 'images/TBD1.jpg' },
                { name: 'T-254', image: 'images/TBD1.jpg' },
                { name: 'T-254-A', image: 'images/TBD1.jpg' },
                { name: 'T-254-H', image: 'images/TBD1.jpg' },
                { name: 'T-255', image: 'images/TBD1.jpg' },
                { name: 'T-2557', image: 'images/CORNISA/T-2557.png' },
                { name: 'T-2557-A', image: 'images/TBD1.jpg' },
                { name: 'T-2557-H', image: 'images/TBD1.jpg' },
                { name: 'T-2557N-W', image: 'images/TBD1.jpg' },
                { name: 'T-2557N-W-A', image: 'images/TBD1.jpg' },
                { name: 'T-2557N-W-H', image: 'images/CORNISA/T-2557N-W-H.png' },
                { name: 'T-255-A', image: 'images/TBD1.jpg' },
                { name: 'T-255-H', image: 'images/TBD1.jpg' },
                { name: 'T-256', image: 'images/TBD1.jpg' },
                { name: 'T-257', image: 'images/CORNISA/T-257.png' },
                { name: 'T-2570', image: 'images/TBD1.jpg' },
                { name: 'T-2571', image: 'images/TBD1.jpg' },
                { name: 'T-2572', image: 'images/TBD1.jpg' },
                { name: 'T-2573', image: 'images/TBD1.jpg' },
                { name: 'T-2574', image: 'images/TBD1.jpg' },
                { name: 'T-258', image: 'images/TBD1.jpg' },
                { name: 'T-2590-H', image: 'images/TBD1.jpg' },
                { name: 'T-2592', image: 'images/TBD1.jpg' },
                { name: 'T-2592-A', image: 'images/TBD1.jpg' },
                { name: 'T-2592-H', image: 'images/TBD1.jpg' },
                { name: 'T-2593', image: 'images/TBD1.jpg' },
                { name: 'T-2593-A', image: 'images/TBD1.jpg' },
                { name: 'T-2593-H', image: 'images/TBD1.jpg' },
                { name: 'T-2594', image: 'images/TBD1.jpg' },
                { name: 'T-2595', image: 'images/TBD1.jpg' },
                { name: 'T-2595-A', image: 'images/TBD1.jpg' },
                { name: 'T-2595-H', image: 'images/TBD1.jpg' },
                { name: 'T-2598', image: 'images/TBD1.jpg' },
                { name: 'T-2598-H', image: 'images/TBD1.jpg' },
                { name: 'T-2599', image: 'images/TBD1.jpg' },
                { name: 'T-2599-H', image: 'images/TBD1.jpg' },
                { name: 'T-PB304', image: 'images/TBD1.jpg' },

                { name: 'U01', image: 'images/CORNISA/U01.jpg' },
                { name: 'U01-C', image: 'images/TBD1.jpg' },
                { name: 'U01-K', image: 'images/TBD1.jpg' },
                { name: 'U-207T', image: 'images/TBD1.jpg' },
                { name: 'U-2504', image: 'images/TBD1.jpg' },
                { name: 'U-251', image: 'images/TBD1.jpg' },
                { name: 'U-251-A', image: 'images/TBD1.jpg' },
                { name: 'U-253', image: 'images/TBD1.jpg' },
                { name: 'U-253-H', image: 'images/TBD1.jpg' },
                { name: 'U-254', image: 'images/TBD1.jpg' },
                { name: 'U-254-H', image: 'images/TBD1.jpg' },
                { name: 'U-254-A', image: 'images/TBD1.jpg' },
                { name: 'U-254-H', image: 'images/TBD1.jpg' },
                { name: 'U-255', image: 'images/TBD1.jpg' },
                { name: 'U-255-H', image: 'images/TBD1.jpg' },
                { name: 'U-2557', image: 'images/TBD1.jpg' },
                { name: 'U-2557-A', image: 'images/TBD1.jpg' },
                { name: 'U-2557N-W', image: 'images/TBD1.jpg' },
                { name: 'U-2557N-W-A', image: 'images/TBD1.jpg' },
                { name: 'U-2557N-W-H', image: 'images/CORNISA/U-2557N-W-H.png' },
                { name: 'U-255-A', image: 'images/TBD1.jpg' },
                { name: 'U-2570', image: 'images/TBD1.jpg' },
                { name: 'U-2571', image: 'images/TBD1.jpg' },
                { name: 'U-2572', image: 'images/TBD1.jpg' },
                { name: 'U-2573', image: 'images/TBD1.jpg' },
                { name: 'U-2574', image: 'images/TBD1.jpg' },
                { name: 'U-258', image: 'images/TBD1.jpg' },
                { name: 'U-2590-H', image: 'images/TBD1.jpg' },
                { name: 'U-2592-A', image: 'images/TBD1.jpg' },
                { name: 'U-2593-A', image: 'images/TBD1.jpg' },
                { name: 'U-2593-H', image: 'images/TBD1.jpg' },
                { name: 'U-2595', image: 'images/TBD1.jpg' },
                { name: 'U-2595-A', image: 'images/TBD1.jpg' },
                { name: 'U-2595-H', image: 'images/TBD1.jpg' },
                { name: 'UP01', image: 'images/TBD1.jpg' },

                { name: 'F01', image: 'images/CORNISA/F01.jpg' },
                { name: 'F01-K', image: 'images/TBD1.jpg' },
                { name: 'F-251', image: 'images/TBD1.jpg' },
                { name: 'F-251 P', image: 'images/TBD1.jpg' },
                { name: 'F-253', image: 'images/TBD1.jpg' },
                { name: 'F-253 P', image: 'images/TBD1.jpg' },
                { name: 'F-255', image: 'images/TBD1.jpg' },
                { name: 'F-255 P', image: 'images/TBD1.jpg' },
                { name: 'F-2557N-w', image: 'images/TBD1.jpg' },
                { name: 'F-2570', image: 'images/TBD1.jpg' },
                { name: 'F-2572', image: 'images/TBD1.jpg' },
                { name: 'F-2573', image: 'images/TBD1.jpg' },
                { name: 'F-2574', image: 'images/TBD1.jpg' },
                { name: 'F-2592', image: 'images/TBD1.jpg' },
                { name: 'F-2598', image: 'images/TBD1.jpg' },
                { name: 'F-2599', image: 'images/TBD1.jpg' },

                { name: 'AF-01-B', image: 'images/CORNISA/AF-01-B.jpg' },
                { name: 'AF-01-M', image: 'images/CORNISA/AF-01-M.jpg' },
                { name: 'AF-02', image: 'images/TBD1.jpg' },
                { name: 'AF-03', image: 'images/TBD1.jpg' },
                { name: 'AF-04', image: 'images/TBD1.jpg' },
                { name: 'AF-05', image: 'images/TBD1.jpg' },
                { name: 'AF-06', image: 'images/TBD1.jpg' },
                { name: 'AF-07', image: 'images/TBD1.jpg' },
                { name: 'UA-C91', image: 'images/TBD1.jpg' },
                { name: 'UA-R224', image: 'images/TBD1.jpg' },
                { name: 'UA-R585', image: 'images/TBD1.jpg' },
                { name: 'UA-R767', image: 'images/TBD1.jpg' },
                { name: 'UA-R781', image: 'images/TBD1.jpg' },

                { name: 'H01', image: 'images/CORNISA/H01.jpg' },
                { name: 'H01-C', image: 'images/TBD1.jpg' },
                { name: 'H01-K', image: 'images/TBD1.jpg' },
                { name: 'H10', image: 'images/TBD1.jpg' },
                { name: 'H-205T', image: 'images/TBD1.jpg' },
                { name: 'H-207T', image: 'images/TBD1.jpg' },
                { name: 'H-251', image: 'images/TBD1.jpg' },
                { name: 'H-251-A', image: 'images/TBD1.jpg' },
                { name: 'H-253', image: 'images/TBD1.jpg' },
                { name: 'H-254', image: 'images/TBD1.jpg' },
                { name: 'H-254-A', image: 'images/TBD1.jpg' },
                { name: 'H-254-H', image: 'images/TBD1.jpg' },
                { name: 'H-255', image: 'images/TBD1.jpg' },
                { name: 'H-2557', image: 'images/TBD1.jpg' },
                { name: 'H-2557-A', image: 'images/TBD1.jpg' },
                { name: 'H-2557-H', image: 'images/TBD1.jpg' },
                { name: 'H-2557N-W', image: 'images/TBD1.jpg' },
                { name: 'H-2557N-W-A', image: 'images/TBD1.jpg' },
                { name: 'H-255-A', image: 'images/TBD1.jpg' },
                { name: 'H-256', image: 'images/TBD1.jpg' },
                { name: 'H-2570', image: 'images/TBD1.jpg' },
                { name: 'H-2571', image: 'images/TBD1.jpg' },
                { name: 'H-2572', image: 'images/TBD1.jpg' },
                { name: 'H-2573', image: 'images/TBD1.jpg' },
                { name: 'H-2574', image: 'images/TBD1.jpg' },
                { name: 'H-258', image: 'images/TBD1.jpg' },
                { name: 'H-2590-H', image: 'images/TBD1.jpg' },
                { name: 'H-2592', image: 'images/TBD1.jpg' },
                { name: 'H-2592-A', image: 'images/TBD1.jpg' },
                { name: 'H-2592-H', image: 'images/TBD1.jpg' },
                { name: 'H-2593', image: 'images/TBD1.jpg' },
                { name: 'H-2593-A', image: 'images/TBD1.jpg' },
                { name: 'H-2593-H', image: 'images/TBD1.jpg' },
                { name: 'H-2595', image: 'images/TBD1.jpg' },
                { name: 'H-2595-A', image: 'images/TBD1.jpg' },
                { name: 'H-2595-H', image: 'images/TBD1.jpg' },
                { name: 'H-2597-H', image: 'images/TBD1.jpg' },
                { name: 'H-2598', image: 'images/TBD1.jpg' },
                { name: 'H-2598-H', image: 'images/TBD1.jpg' },
                { name: 'H-2599', image: 'images/TBD1.jpg' },
                { name: 'H-BV615', image: 'images/TBD1.jpg' },
                { name: 'HP01', image: 'images/TBD1.jpg' },
                { name: 'H-PB304', image: 'images/TBD1.jpg' },

                { name: 'CIN-1', image: 'images/TBD1.jpg' },
                { name: 'CIN-3', image: 'images/TBD1.jpg' },
                { name: 'CIN-7', image: 'images/TBD1.jpg' },
                { name: 'CIN-CONTRUTEC', image: 'images/TBD1.jpg' },
                { name: 'PE-6', image: 'images/TBD1.jpg' },

                { name: 'CIN-1', image: 'images/TBD1.jpg' },
                { name: 'CIN-3', image: 'images/TBD1.jpg' },
                { name: 'CIN-7', image: 'images/TBD1.jpg' },
                { name: 'CIN-CONTRUTEC', image: 'images/TBD1.jpg' },
                { name: 'PE-6', image: 'images/TBD1.jpg' },
                //PLACA DE YESO
                { name: 'PLACA-KN1', image: 'images/TBD1.jpg' },
                { name: 'PLACA-KN2', image: 'images/TBD1.jpg' },
                { name: 'PLACA-KN3', image: 'images/TBD1.jpg' },
                //MASILLA
                { name: 'MASILLA-S1', image: 'images/TBD1.jpg' },
                //AUTO ADHESIVA
                { name: '59-006', image: 'images/The-3D/AUTO-ADHESIVA/59-006.jpg' },
                { name: '69-001', image: 'images/TBD1.jpg' },
                { name: '8103', image: 'images/The-3D/AUTO-ADHESIVA/8103.jpg' },
                { name: '8104', image: 'images/The-3D/AUTO-ADHESIVA/8104.jpg' },
                { name: '8107', image: 'images/The-3D/AUTO-ADHESIVA/8107.jpg' },
                { name: '83-001', image: 'images/TBD1.jpg' },
                { name: '83-005', image: 'images/TBD1.jpg' },
                { name: 'AA-A6', image: 'images/The-3D/AUTO-ADHESIVA/AA-A6.jpg' },
                { name: 'AA-AC6', image: 'images/The-3D/AUTO-ADHESIVA/AA-AC6.jpg' },
                { name: 'AA-AG6', image: 'images/The-3D/AUTO-ADHESIVA/AA-AG6.jpg' },
                { name: 'AA-AG6-1', image: 'images/TBD1.jpg' },
                { name: 'AA-B3', image: 'images/The-3D/AUTO-ADHESIVA/AA-B3.jpg' },
                { name: 'AA-B6', image: 'images/The-3D/AUTO-ADHESIVA/AA-B6.jpg' },
                { name: 'AA-B6-1', image: 'images/TBD1.jpg' },
                { name: 'AA-C01', image: 'images/The-3D/AUTO-ADHESIVA/AA-C01.jpg' },
                { name: 'AA-C02', image: 'images/The-3D/AUTO-ADHESIVA/AA-C02.jpg' },
                { name: 'AA-C03', image: 'images/The-3D/AUTO-ADHESIVA/AA-C03.jpg' },
                { name: 'AA-GJ8', image: 'images/TBD1.jpg' },
                { name: 'AA-GV6', image: 'images/The-3D/AUTO-ADHESIVA/AA-GV6.jpg' },
                { name: 'AA-MM6', image: 'images/The-3D/AUTO-ADHESIVA/AA-MM6.jpg' },
                { name: 'AA-MN6', image: 'images/The-3D/AUTO-ADHESIVA/AA-MN6.jpg' },
                { name: 'AA-N3', image: 'images/TBD1.jpg' },
                { name: 'AA-N6-C', image: 'images/The-3D/AUTO-ADHESIVA/AA-N6.jpg' },
                { name: 'AA-N6-O', image: 'images/The-3D/AUTO-ADHESIVA/AA-N6.jpg' },
                { name: 'AA-PG6', image: 'images/The-3D/AUTO-ADHESIVA/AA-PG6.jpg' },
                { name: 'AA-PG6-1', image: 'images/TBD1.jpg' },
                { name: 'AA-PM6', image: 'images/The-3D/AUTO-ADHESIVA/AA-PM6.jpg' },
                { name: 'AA-PR6', image: 'images/The-3D/AUTO-ADHESIVA/AA-PR6.jpg' },
                { name: 'AA-PV6', image: 'images/The-3D/AUTO-ADHESIVA/AA-PV6.jpg' },
                { name: 'AA-RC6', image: 'images/The-3D/AUTO-ADHESIVA/AA-RC6.jpg' },
                { name: 'AA-YS8', image: 'images/TBD1.jpg' },
                { name: 'AA-Z206', image: 'images/The-3D/AUTO-ADHESIVA/AA-Z206.jpg' },
                { name: 'AA-Z216', image: 'images/The-3D/AUTO-ADHESIVA/AA-Z216.jpg' },
                { name: 'AD-56', image: 'images/The-3D/AUTO-ADHESIVA/AD-56.jpg' },
                { name: 'CS-001', image: 'images/The-3D/AUTO-ADHESIVA/CS-001.jpg' },
                { name: 'CS-002', image: 'images/The-3D/AUTO-ADHESIVA/CS-002.jpg' },
                { name: 'CS-010', image: 'images/The-3D/AUTO-ADHESIVA/CS-010.jpg' },
                { name: 'CS-011', image: 'images/TBD1.jpg' },
                { name: 'CS-014', image: 'images/The-3D/AUTO-ADHESIVA/CS-014.jpg' },
                { name: 'ESTRELLA ROSA', image: 'images/The-3D/AUTO-ADHESIVA/Estrella-Rosa.jpg' },
                { name: 'FC-28', image: 'images/TBD1.jpg' },
                { name: 'FC-31', image: 'images/TBD1.jpg' },
                { name: 'FC-60', image: 'images/The-3D/AUTO-ADHESIVA/FC-60.jpg' },
                { name: 'FC-60-1', image: 'images/TBD1.jpg' },
                { name: 'FC-76', image: 'images/TBD1.jpg' },
                { name: 'FC-88', image: 'images/The-3D/AUTO-ADHESIVA/FC-88.jpg' },
                { name: 'HG-066', image: 'images/TBD1.jpg' },
                { name: 'HG-53', image: 'images/The-3D/AUTO-ADHESIVA/HG-53.jpg' },
                { name: 'HG-53-001', image: 'images/The-3D/AUTO-ADHESIVA/HG-53-001.jpg' },
                { name: 'HG-54-001', image: 'images/The-3D/AUTO-ADHESIVA/HG-54-001.jpg' },
                { name: 'HG-56-005', image: 'images/The-3D/AUTO-ADHESIVA/HG-56-005.jpg' },
                { name: 'HG-57', image: 'images/TBD1.jpg' },
                { name: 'HG-58-001', image: 'images/TBD1.jpg' },
                { name: 'HG-58-011', image: 'images/The-3D/AUTO-ADHESIVA/HG-58-011.jpg' },
                { name: 'HG-59', image: 'images/TBD1.jpg' },
                { name: 'HG61', image: 'images/TBD1.jpg' },
                { name: 'HG61-002', image: 'images/The-3D/AUTO-ADHESIVA/HG61-002.jpg' },
                { name: 'HG-61-010', image: 'images/The-3D/AUTO-ADHESIVA/HG-61-010.jpg' },
                { name: 'HG61-010', image: 'images/TBD1.jpg' },
                { name: 'HG-62-004', image: 'images/The-3D/AUTO-ADHESIVA/HG-62-004.jpg' },
                { name: 'HG-63', image: 'images/TBD1.jpg' },
                { name: 'HG-64-001', image: 'images/TBD1.jpg' },
                { name: 'HG-65', image: 'images/TBD1.jpg' },
                { name: 'HG-65-010', image: 'images/The-3D/AUTO-ADHESIVA/HG-65-010.jpg' },
                { name: 'HG-75', image: 'images/TBD1.jpg' },
                { name: 'HG-78', image: 'images/TBD1.jpg' },
                { name: 'HG-78-003', image: 'images/The-3D/AUTO-ADHESIVA/HG-78-003.jpg' },
                { name: 'HG-79', image: 'images/TBD1.jpg' },
                { name: 'HG-80-005', image: 'images/The-3D/AUTO-ADHESIVA/HG-80-005.jpg' },
                { name: 'HG-80-011', image: 'images/The-3D/AUTO-ADHESIVA/HG-80-011.jpg' },
                { name: 'HG-81', image: 'images/TBD1.jpg' },
                { name: 'HG-8106', image: 'images/The-3D/AUTO-ADHESIVA/HG-8106.jpg' },
                { name: 'HG-83', image: 'images/TBD1.jpg' },
                { name: 'HG-83-001', image: 'images/TBD1.jpg' },
                { name: 'HG-9032', image: 'images/The-3D/AUTO-ADHESIVA/HG-9032.jpg' },
                { name: 'HG-9087', image: 'images/The-3D/AUTO-ADHESIVA/HG-9087.jpg' },
                { name: 'HG-9091', image: 'images/The-3D/AUTO-ADHESIVA/HG-9091.jpg' },
                { name: 'HG-9092', image: 'images/The-3D/AUTO-ADHESIVA/HG-9092.jpg' },
                { name: 'HG-9094', image: 'images/The-3D/AUTO-ADHESIVA/HG-9094.jpg' },
                { name: 'HG-9097', image: 'images/The-3D/AUTO-ADHESIVA/HG-9097.jpg' },
                { name: 'HG-9099', image: 'images/The-3D/AUTO-ADHESIVA/HG-9099.jpg' },
                { name: 'HG-9103', image: 'images/The-3D/AUTO-ADHESIVA/HG-9103.jpg' },
                { name: 'KT-001', image: 'images/The-3D/AUTO-ADHESIVA/KT-001.jpg' },
                { name: 'KT-003', image: 'images/TBD1.jpg' },
                { name: 'KT-004', image: 'images/The-3D/AUTO-ADHESIVA/KT-004.jpg' },
                { name: 'KT-004-2', image: 'images/The-3D/AUTO-ADHESIVA/KT-004-2.jpg' },
                { name: 'KT-005', image: 'images/The-3D/AUTO-ADHESIVA/KT-005.jpg' },
                { name: 'KT-007', image: 'images/The-3D/AUTO-ADHESIVA/ZW-KT-007-KT-58-007.jpg' },
                { name: 'KT-010', image: 'images/The-3D/AUTO-ADHESIVA/KT-010.jpg' },
                { name: 'KT-011', image: 'images/The-3D/AUTO-ADHESIVA/KT-011.jpg' },
                { name: 'KT-012', image: 'images/TBD1.jpg' },
                { name: 'KT-014', image: 'images/The-3D/AUTO-ADHESIVA/KT-014.jpg' },
                { name: 'KT-015', image: 'images/TBD1.jpg' },
                { name: 'KT-016', image: 'images/The-3D/AUTO-ADHESIVA/KT-016.jpg' },
                { name: 'KT-017', image: 'images/The-3D/AUTO-ADHESIVA/KT-017.jpg' },
                { name: 'KT-018', image: 'images/The-3D/AUTO-ADHESIVA/KT-018.jpg' },
                { name: 'KT-019', image: 'images/The-3D/AUTO-ADHESIVA/KT-019.jpg' },
                { name: 'KT-022', image: 'images/The-3D/AUTO-ADHESIVA/KT-022.jpg' },
                { name: 'KT10', image: 'images/TBD1.jpg' },
                { name: 'KT-15', image: 'images/TBD1.jpg' },
                { name: 'KT58-007', image: 'images/TBD1.jpg' },
                { name: 'MW-003', image: 'images/TBD1.jpg' },
                { name: 'MW-006', image: 'images/The-3D/AUTO-ADHESIVA/MW-006.jpg' },
                { name: 'MW-007', image: 'images/TBD1.jpg' },
                { name: 'MW-009', image: 'images/The-3D/AUTO-ADHESIVA/MW-013-MW-009.jpg' },
                { name: 'MW-011', image: 'images/TBD1.jpg' },
                { name: 'MW-013', image: 'images/The-3D/AUTO-ADHESIVA/MW-013-MW-009.jpg' },
                { name: 'MW-03', image: 'images/TBD1.jpg' },
                { name: 'NF-17', image: 'images/TBD1.jpg' },
                { name: 'NF-20', image: 'images/TBD1.jpg' },
                { name: 'NF-23', image: 'images/TBD1.jpg' },
                { name: 'OB-04', image: 'images/TBD1.jpg' },
                { name: 'OB-05', image: 'images/TBD1.jpg' },
                { name: 'OB-06', image: 'images/TBD1.jpg' },
                { name: 'QM-08', image: 'images/TBD1.jpg' },
                { name: 'RBMB01', image: 'images/TBD1.jpg' },
                { name: 'RBXH-01', image: 'images/TBD1.jpg' },
                { name: 'RBXK015-01', image: 'images/TBD1.jpg' },
                { name: 'RBXK015-02', image: 'images/TBD1.jpg' },
                { name: 'RBXK015-03', image: 'images/TBD1.jpg' },
                { name: 'WDRB020-03', image: 'images/TBD1.jpg' },
                { name: 'WDRBO19-ZM04', image: 'images/TBD1.jpg' },
                { name: 'WDRBO19-ZM041', image: 'images/TBD1.jpg' },
                { name: 'WDRBO23-01', image: 'images/TBD1.jpg' },
                { name: 'WDXFC001-01', image: 'images/TBD1.jpg' },
                { name: 'ZW-002', image: 'images/The-3D/AUTO-ADHESIVA/ZW-02.jpg' },
                { name: 'ZW-003', image: 'images/The-3D/AUTO-ADHESIVA/ZW-003.jpg' },
                { name: 'ZW-006', image: 'images/TBD1.jpg' },
                { name: 'ZW-007', image: 'images/The-3D/AUTO-ADHESIVA/ZW-007.jpg' },
                { name: 'ZW-010', image: 'images/TBD1.jpg' },
                { name: 'ZW-011', image: 'images/TBD1.jpg' },
                { name: 'ZW-013', image: 'images/TBD1.jpg' },
                { name: 'ZW-014', image: 'images/TBD1.jpg' },
                { name: 'ZW-016', image: 'images/The-3D/AUTO-ADHESIVA/ZW-016.jpg' },
                { name: 'ZW-018', image: 'images/The-3D/AUTO-ADHESIVA/ZW-018.jpg' },
                { name: 'ZW-020', image: 'images/TBD1.jpg' },
                { name: 'ZW-021', image: 'images/TBD1.jpg' },
                { name: 'ZW-022', image: 'images/TBD1.jpg' },
                { name: 'ZW-023', image: 'images/The-3D/AUTO-ADHESIVA/ZW-023.jpg' },
                { name: 'ZW-024', image: 'images/TBD1.jpg' },
                { name: 'ZW-025', image: 'images/TBD1.jpg' },
                { name: 'ZW-031', image: 'images/The-3D/AUTO-ADHESIVA/ZW-031.jpg' },
                { name: 'ZW-033', image: 'images/The-3D/AUTO-ADHESIVA/ZW-033.jpg' },
                { name: 'ZW-034', image: 'images/TBD1.jpg' },
                { name: 'ZW-040', image: 'images/The-3D/AUTO-ADHESIVA/ZW-040.jpg' },
                { name: 'ZW-043', image: 'images/The-3D/AUTO-ADHESIVA/ZW-043.jpg' },
                { name: 'ZW-047', image: 'images/TBD1.jpg' },
                { name: 'ZW-048', image: 'images/TBD1.jpg' },
                { name: 'ZW-051', image: 'images/TBD1.jpg' },
                { name: 'ZW-054', image: 'images/The-3D/AUTO-ADHESIVA/ZW-054.jpg' },
                { name: 'ZW-14', image: 'images/TBD1.jpg' },
                { name: 'ZW-15', image: 'images/TBD1.jpg' },
                { name: 'ZW-22', image: 'images/The-3D/AUTO-ADHESIVA/ZW-22.jpg' },
                { name: 'ZW-24', image: 'images/The-3D/AUTO-ADHESIVA/ZW-24.jpg' },
                { name: 'ZW-42', image: 'images/The-3D/AUTO-ADHESIVA/ZW-42.jpg' },
                { name: 'ZW-43', image: 'images/TBD1.jpg' },
                { name: 'ZW-50', image: 'images/TBD1.jpg' },
                { name: 'ZW-54', image: 'images/TBD1.jpg' },
                { name: 'ZWH001', image: 'images/TBD1.jpg' },
                { name: 'ZWH006', image: 'images/TBD1.jpg' },
                { name: 'ZWH010', image: 'images/TBD1.jpg' },
                { name: 'ZWH020', image: 'images/TBD1.jpg' },
                { name: 'ZWH023', image: 'images/TBD1.jpg' },
                { name: 'ZWH026', image: 'images/TBD1.jpg' },
                { name: 'ZWH038', image: 'images/TBD1.jpg' },
                { name: 'ZWH049', image: 'images/TBD1.jpg' },
                { name: 'ZWH059', image: 'images/TBD1.jpg' },
                { name: 'ZWH062', image: 'images/TBD1.jpg' },
                { name: 'ZWH067', image: 'images/TBD1.jpg' },
                { name: 'ZWH076', image: 'images/TBD1.jpg' },
                { name: 'ZWH086', image: 'images/TBD1.jpg' },
                { name: 'ZW-KT-007', image: 'images/TBD1.jpg' },
                //LAMINA MARMOLADA AUTO ADHESIVA
                { name: '6031', image: 'images/The-3D/LAMINA-MARMOLADA-AUTO-ADHESIVA/6031.png' },
                { name: '6156', image: 'images/The-3D/LAMINA-MARMOLADA-AUTO-ADHESIVA/6156.png' },
                { name: '6180-3', image: 'images/TBD1.jpg' },
                { name: '6191', image: 'images/The-3D/LAMINA-MARMOLADA-AUTO-ADHESIVA/6191.png' },
                { name: 'YP103', image: 'images/The-3D/LAMINA-MARMOLADA-AUTO-ADHESIVA//YP-103.png' },
                { name: 'YP104', image: 'images/The-3D/LAMINA-MARMOLADA-AUTO-ADHESIVA//YP-104.png' },
                { name: 'YP108', image: 'images/TBD1.jpg' },
                { name: 'YP-30', image: 'images/TBD1.jpg' },
                { name: 'YP-44', image: 'images/TBD1.jpg' },
                { name: 'YP-76', image: 'images/TBD1.jpg' },
                { name: 'YP-95', image: 'images/TBD1.jpg' },
                //ADHESIVO EN ROLLO
                { name: 'JC-03', image: 'images/The-3D/ADHESIVO-EN-ROLLO/JC-03.png' },
                { name: 'JC-04', image: 'images/The-3D/ADHESIVO-EN-ROLLO/JC-04.jpg' },
                { name: 'JC-05', image: 'images/The-3D/ADHESIVO-EN-ROLLO/JC-05.png' },
                //LAMINA 3D
                { name: 'D003-1', image: 'images/TBD1.jpg' },
                { name: 'D017', image: 'images/The-3D/LAMINA-3D/D017.jpg' },
                { name: 'D078', image: 'images/The-3D/LAMINA-3D/D078.jpg' },
                { name: 'D088', image: 'images/TBD1.jpg' },
                { name: 'D091', image: 'images/TBD1.jpg' },
                { name: 'D094', image: 'images/The-3D/LAMINA-3D/D094.jpg' },
                { name: 'D094-ML', image: 'images/The-3D/LAMINA-3D/D094-ML.jpg' },
                { name: 'D095', image: 'images/The-3D/LAMINA-3D/D095.jpg' },
                { name: 'D099', image: 'images/TBD1.jpg' },
                { name: 'D100', image: 'images/The-3D/LAMINA-3D/D100.jpg' },
                { name: 'D106', image: 'images/The-3D/LAMINA-3D/D106.jpg' },
                { name: 'D111', image: 'images/TBD1.jpg' },
                { name: 'D124', image: 'images/The-3D/LAMINA-3D/D124.jpg' },
                { name: 'D125', image: 'images/TBD1.jpg' },
                { name: 'D137', image: 'images/The-3D/LAMINA-3D/D137.jpg' },
                { name: 'D140', image: 'images/The-3D/LAMINA-3D/D140.jpg' },
                { name: 'D142', image: 'images/The-3D/LAMINA-3D/D142.jpg' },
                { name: 'D143', image: 'images/The-3D/LAMINA-3D/D143.jpg' },
                { name: 'D146', image: 'images/The-3D/LAMINA-3D/D146.jpg' },
                { name: 'D147', image: 'images/The-3D/LAMINA-3D/D147.jpg' },
                { name: 'D151', image: 'images/The-3D/LAMINA-3D/D151.jpg' },
                { name: 'D153', image: 'images/The-3D/LAMINA-3D/D153.jpg' },
                { name: 'D154', image: 'images/The-3D/LAMINA-3D/D154.jpg' },
                { name: 'D156', image: 'images/The-3D/LAMINA-3D/D156.jpg' },
                //PAPEL ADHESIVO
                { name: 'C197-1', image: 'images/TBD1.jpg' },
                { name: 'D001-1', image: 'images/TBD1.jpg' },
                { name: 'D005-1', image: 'images/TBD1.jpg' },
                { name: 'D010-2', image: 'images/TBD1.jpg' },
                { name: 'KN-001', image: 'images/TBD1.jpg' },
                { name: 'KN-002', image: 'images/TBD1.jpg' },
                { name: 'KN-003', image: 'images/TBD1.jpg' },
                { name: 'KN-C0008-3', image: 'images/TBD1.jpg' },
                { name: 'KN-C0014-2', image: 'images/TBD1.jpg' },
                { name: 'KN-C0019-1', image: 'images/TBD1.jpg' },
                { name: 'KN-C0022-1', image: 'images/TBD1.jpg' },
                { name: 'KN-C0024-1', image: 'images/TBD1.jpg' },
                { name: 'KN-C0024-2', image: 'images/TBD1.jpg' },
                { name: 'KN-C0024-3', image: 'images/TBD1.jpg' },
                { name: 'KN-C0024-4', image: 'images/TBD1.jpg' },
                { name: 'KN-C0026-1', image: 'images/TBD1.jpg' },
                { name: 'KN-C0026-2', image: 'images/TBD1.jpg' },
                { name: 'KN-C0026-3', image: 'images/TBD1.jpg' },
                { name: 'KN-C0027-1', image: 'images/TBD1.jpg' },
                { name: 'KN-M0004-1', image: 'images/TBD1.jpg' },
                { name: 'KN-M0004-2', image: 'images/TBD1.jpg' },
                { name: 'KN-M0007-1', image: 'images/TBD1.jpg' },
                { name: 'KN-M0011-1', image: 'images/TBD1.jpg' },
                { name: 'KN-M0011-2', image: 'images/TBD1.jpg' },
                { name: 'KN-M0011-3', image: 'images/TBD1.jpg' },
                { name: 'KN-M0011-4', image: 'images/TBD1.jpg' },
                { name: 'KN-M0014-1', image: 'images/TBD1.jpg' },
                { name: 'KN-M0018-1', image: 'images/TBD1.jpg' },
                { name: 'KN-M0023-1', image: 'images/TBD1.jpg' },
                { name: 'KN-M0023-2', image: 'images/TBD1.jpg' },
                { name: 'KN-M0024-1', image: 'images/TBD1.jpg' },
                { name: 'KN-M0025-2', image: 'images/TBD1.jpg' },
                { name: 'KN-M0028-2', image: 'images/TBD1.jpg' },
                { name: 'KN-M0029-1', image: 'images/TBD1.jpg' },
                { name: 'KN-M0030-4', image: 'images/TBD1.jpg' },
                { name: 'KN-M0038-1', image: 'images/TBD1.jpg' },
                { name: 'KN-M0038-3', image: 'images/TBD1.jpg' },
                { name: 'KN-W0001-1', image: 'images/TBD1.jpg' },
                { name: 'KN-W0001-2', image: 'images/TBD1.jpg' },
                { name: 'KN-W0001-3', image: 'images/TBD1.jpg' },
                { name: 'KN-W0001-4', image: 'images/TBD1.jpg' },
                { name: 'KN-W0002-1', image: 'images/TBD1.jpg' },
                { name: 'KN-W0002-2', image: 'images/TBD1.jpg' },
                { name: 'KN-W0003-4', image: 'images/TBD1.jpg' },
                { name: 'KN-W0004-3', image: 'images/TBD1.jpg' },
                { name: 'KN-W0009-2', image: 'images/TBD1.jpg' },
                { name: 'KN-W0020-1', image: 'images/TBD1.jpg' },
                { name: 'KN-W0028-1', image: 'images/TBD1.jpg' },
                { name: 'KN-W0028-3', image: 'images/TBD1.jpg' },
                { name: 'KN-W0031-1', image: 'images/TBD1.jpg' },
                { name: 'KN-W0033-4', image: 'images/TBD1.jpg' },
                { name: 'KN-W0034-4', image: 'images/TBD1.jpg' },
                { name: 'KN-W0038-2', image: 'images/TBD1.jpg' },
                { name: 'KN-X0033-1', image: 'images/TBD1.jpg' },
                { name: 'KN-X0070-1', image: 'images/TBD1.jpg' },
                { name: 'KN-X0182-1', image: 'images/TBD1.jpg' },
                { name: 'KN-X0195-3', image: 'images/TBD1.jpg' },
                //VINILO ADHESIVO PARA VIDRIO
                { name: 'VAV-01', image: 'images/TBD1.jpg' },
                { name: 'VAV-02', image: 'images/TBD1.jpg' },
                { name: 'VAV-03', image: 'images/TBD1.jpg' },
                { name: 'VAV-04', image: 'images/TBD1.jpg' },
                //ZOCALO AUTO ADHESIVA
                { name: 'ZA-01', image: 'images/TBD1.jpg' },
                { name: 'ZA-02', image: 'images/TBD1.jpg' },
                //Placas de Pvc marmolados,2.44m*1.22m*3mm
                { name: 'BV1201', image: 'images/REVESTIMIENTO/BV1201.png' },                
                { name: 'BV1202', image: 'images/REVESTIMIENTO/BV1202.jpg' },
                { name: 'BV1203', image: 'images/REVESTIMIENTO/BV1203.png' },
                { name: 'BV1204', image: 'images/REVESTIMIENTO/BV1204.png' },
                { name: 'BV1205', image: 'images/REVESTIMIENTO/BV1205.png' },
                { name: 'BV1206', image: 'images/REVESTIMIENTO/BV1206.png' },
                { name: 'BV1207', image: 'images/REVESTIMIENTO/BV1207.png' },
                { name: 'BV1208', image: 'images/REVESTIMIENTO/BV1208.png' },
                { name: 'BV1209', image: 'images/REVESTIMIENTO/BV1209.png' },
                { name: 'BV1210', image: 'images/REVESTIMIENTO/BV1210.png' },
                { name: 'BV1211', image: 'images/REVESTIMIENTO/BV1211.png' },
                { name: 'BV1212', image: 'images/REVESTIMIENTO/BV1212.png' },
                { name: 'BV1213', image: 'images/REVESTIMIENTO/BV1213.png' },
                { name: 'BV1219', image: 'images/TBD1.jpg' },
                { name: 'BV1220', image: 'images/TBD1.jpg' },
                { name: 'BV1221', image: 'images/TBD1.jpg' },
                { name: 'BV1222', image: 'images/TBD1.jpg' },
                { name: 'BV1223', image: 'images/TBD1.jpg' },
                { name: 'BV1224', image: 'images/TBD1.jpg' },
                { name: 'BV1225', image: 'images/TBD1.jpg' },
                { name: 'BV1226', image: 'images/TBD1.jpg' },
                { name: 'BV1227', image: 'images/TBD1.jpg' },
                //Revestimiento Int. PVC 40cm*9mm*2.95m
                { name: 'BV403', image: 'images/TBD1.jpg'  },                
                { name: 'BV404', image: 'images/REVESTIMIENTO/BV404.jpg' },
                { name: 'BV494', image: 'images/REVESTIMIENTO/BV494-H.jpg' },
                { name: 'BV496', image: 'images/REVESTIMIENTO/BV496.jpg' },
                //Revestimiento Int. PVC 60cm*8mm*2.95m
                { name: 'BV601', image: 'images/REVESTIMIENTO/BV601-H.jpg' },
                { name: 'BV601-H', image: 'images/REVESTIMIENTO/BV601-H.jpg' },                
                { name: 'BV603', image: 'images/REVESTIMIENTO/BV603.jpg' },
                { name: 'BV604', image: 'images/REVESTIMIENTO/BV604.jpg' },
                { name: 'BV605', image: 'images/REVESTIMIENTO/BV605.jpg' },
                { name: 'BV606', image: 'images/REVESTIMIENTO/BV606.jpg' },
                { name: 'BV607', image: 'images/REVESTIMIENTO/BV607.jpg' },
                { name: 'BV608', image: 'images/REVESTIMIENTO/BV608.jpg' },
                { name: 'BV609', image: 'images/REVESTIMIENTO/BV609.jpg' },
                { name: 'BV610', image: 'images/REVESTIMIENTO/BV610.jpg' },
                { name: 'BV611', image: 'images/REVESTIMIENTO/BV611.jpg' },
                { name: 'BV612', image: 'images/REVESTIMIENTO/BV612.jpg' },
                { name: 'BV614', image: 'images/REVESTIMIENTO/BV614.jpg' },
                { name: 'BV615', image: 'images/REVESTIMIENTO/BV615.jpg' },
                { name: 'BV616', image: 'images/REVESTIMIENTO/BV616.jpg' },
                { name: 'BV617', image: 'images/REVESTIMIENTO/BV617-H.jpg' },
                { name: 'BV617-H', image: 'images/REVESTIMIENTO/BV617-H.jpg' },
                { name: 'BV619', image: 'images/REVESTIMIENTO/BV619.jpg' },
                { name: 'BV620', image: 'images/REVESTIMIENTO/BV620.jpg' },
                { name: 'BV659', image: 'images/REVESTIMIENTO/BV659-H.jpg' },
                { name: 'BV659-H', image: 'images/REVESTIMIENTO/BV659-H.jpg' },
                //Lamina tipo espejo 2.44m*1.22m*5mm
                { name: 'EDE-01', image: 'images/TBD1.jpg' },
                //Panel De Aluminio 1.22M*2.8M*7MM
                { name: 'NA-01', image: 'images/REVESTIMIENTO/NA-01.jpg' },
                //Panel De Aluminio 1.22M*2.9M*7MM
                { name: 'NA-02', image: 'images/REVESTIMIENTO/NA-02.jpg' }, 
                { name: 'NA-04', image: 'images/REVESTIMIENTO/NA-04.jpg' },              
                { name: 'NA-05', image: 'images/REVESTIMIENTO/NA-05.jpg' },
                { name: 'NA-06', image: 'images/REVESTIMIENTO/NA-06.jpg' },
                { name: 'NA-07', image: 'images/REVESTIMIENTO/NA-07.jpg' },
                { name: 'NA-08', image: 'images/REVESTIMIENTO/NA-08.jpg' }, 
                { name: 'NA-09', image: 'images/REVESTIMIENTO/NA-09.jpg' },
                //Policarbonado solido 1220mm*2440mm*3mm
                { name: 'PS01', image: 'images/TBD1.jpg' },
                //Roca PU 1.2m*0.6m*3cm
                { name: 'PUA-3-1', image: 'images/REVESTIMIENTO/PUA-31.jpg' },                
                { name: 'PUA-3-12', image: 'images/TBD1.jpg' },
                { name: 'PUA-3-4', image: 'images/REVESTIMIENTO/PUA-34.jpg' },
                { name: 'PUA-3-6', image: 'images/REVESTIMIENTO/PUA-36.jpg' },
                { name: 'PUA-3-7', image: 'images/REVESTIMIENTO/PUA-37.jpg' },                
                { name: 'PUA-4-3', image: 'images/TBD1.jpg' },
                //Revestimiento Ext. 3,85m*35cm*16mm
                { name: 'RPE-08', image: 'images/TBD1.jpg' },
                //Revestimiento Ext. 3,85m*38cm*16mm
                { name: 'RPE-01', image: 'images/REVESTIMIENTO/RPE-01.jpg' },                
                { name: 'RPE-02', image: 'images/REVESTIMIENTO/RPE-02.jpg' },
                { name: 'RPE-03', image: 'images/REVESTIMIENTO/RPE-03.jpg' },
                { name: 'RPE-04', image: 'images/REVESTIMIENTO/RPE-04.jpg' },
                { name: 'RPE-05', image: 'images/REVESTIMIENTO/RPE-05.jpg'},
                { name: 'RPE-06', image: 'images/REVESTIMIENTO/RPE-06.jpg' },
                //Revestimiento Ext. 3,85m*39cm*16mm
                { name: 'RPE-07', image: 'images/TBD1.jpg' },
                //Tubos Divisorios <br>de WPC
                { name: 'TC-01', image: 'images/REVESTIMIENTO/TC-01-TD-01.png' },                
                { name: 'TC-02', image: 'images/REVESTIMIENTO/TC-02-TD-02.png' },
                { name: 'TC-07', image: 'images/REVESTIMIENTO/TC-07-TD-07.png' },
                { name: 'TC-09', image: 'images/REVESTIMIENTO/TC-09-TD-09.png' },
                { name: 'TD-01', image: 'images/REVESTIMIENTO/TC-01-TD-01.png' },
                { name: 'TD-02', image: 'images/REVESTIMIENTO/TC-02-TD-02.png' },
                { name: 'TD-07', image: 'images/REVESTIMIENTO/TC-07-TD-07.png' },
                { name: 'TD-09', image: 'images/REVESTIMIENTO/TC-09-TD-09.png' },
                { name: 'WPF-01', image: 'images/REVESTIMIENTO/WPF-01.jpg' },
                { name: 'WPF-03', image: 'images/REVESTIMIENTO/WPF-03.jpg' },
                //Wall Panel de PVC Ripado 15cm*15mm*2.9m
                { name: 'WP-14', image: 'images/REVESTIMIENTO/WP-14.jpg' },                
                { name: 'WP-15', image: 'images/REVESTIMIENTO/WP-15.jpg' },
                //Wall Panel de PVC Ripado 16cm*16mm*2.9m
                { name: 'WP-11', image: 'images/REVESTIMIENTO/WP-11.jpg' },                
                { name: 'WP-12', image: 'images/TBD1.jpg' },
                //Wall Panel de PVC Ripado 16cm*24mm*2.9m
                { name: 'WP-01', image: 'images/REVESTIMIENTO/WP-01.jpg' },                
                { name: 'WP-02', image: 'images/REVESTIMIENTO/WP-02.jpg' },
                { name: 'WP-03', image: 'images/REVESTIMIENTO/WP-03.jpg' },                
                { name: 'WP-04', image: 'images/REVESTIMIENTO/WP-04.jpg' },
                { name: 'WP-07', image: 'images/REVESTIMIENTO/WP-07.jpg' },                
                { name: 'WP-08', image: 'images/REVESTIMIENTO/WP-08.jpg' },
                { name: 'WP-09', image: 'images/REVESTIMIENTO/WP-09.jpg' },                
                { name: 'WP-10', image: 'images/REVESTIMIENTO/WP-10.jpg' },
                { name: 'WP-13', image: 'images/REVESTIMIENTO/WP-13.jpg' },                
                { name: 'WP-16', image: 'images/REVESTIMIENTO/WP-16.jpg' },
                { name: 'WP-19', image: 'images/REVESTIMIENTO/WP-19.jpg' },                
                { name: 'WP-20', image: 'images/REVESTIMIENTO/WP-20.jpg' },
                { name: 'WP-21', image: 'images/REVESTIMIENTO/WP-21.jpg' },                
                { name: 'WP-22', image: 'images/REVESTIMIENTO/WP-22.jpg' },
                { name: 'WPN-01', image: 'images/REVESTIMIENTO/WPN-01.jpg' }, 
                //Wall Panel de PVC Ripado 20cm*16mm*2.9m
                { name: 'WP-24', image: 'images/REVESTIMIENTO/WP-24-Cherry-A.jpg' },                
                { name: 'WP-25', image: 'images/REVESTIMIENTO/WP-25-A.jpg' },
                { name: 'WP-26', image: 'images/REVESTIMIENTO/WP-26-A.jpg' },  
                //Wall Panel de PVC Ripado 20cm*21mm*2.9m
                { name: 'WP-17', image: 'images/REVESTIMIENTO/WP-17.jpg' },
                //Wall Panel de PVC Ripado 20cm*24mm*2.9m
                { name: 'WP-18', image: 'images/REVESTIMIENTO/WP-18.jpg' },                
                { name: 'WP-28', image: 'images/TBD1.jpg' },
                { name: 'WP-29', image: 'images/TBD1.jpg' },   
                //Tablero De Espuma De PVC 1.22m*2.9m*5mm
                { name: 'XD-0008', image: 'images/REVESTIMIENTO/XD-0008.jpg' },                
                { name: 'XD-0016', image: 'images/REVESTIMIENTO/XD-0016.jpg' },
                { name: 'XD-0017', image: 'images/REVESTIMIENTO/XD-0017.jpg' },
                //Tablero De Espuma De PVC 1.22m*2.9m*8mm
                { name: 'XD-0001', image: 'images/REVESTIMIENTO/XD-0001.jpg' },                
                { name: 'XD-0012', image: 'images/REVESTIMIENTO/XD-0012.jpg' },
                { name: 'XD-0021', image: 'images/REVESTIMIENTO/XD-0021.jpg' },
    ]),
  },
  getters: {
    getCart(state){
      return state.cart;
    },
    getUserName(state){
      return state.username;
    },
    getAddress(state){
      return state.address;
    },
    getProductDict(state){
      return state.productDict;
    },
  },
  //同步方法
  mutations: {
    updateCart(state, cart){
      state.cart = cart;
    },
    updateUserName(state, username){
      state.username = username;
    },
    updateAddress(state, address){
      state.address = address;
    },
    updateProductDict(state, productDict){
      state.productDict = productDict;
    },
  },
  //异步方法
  actions: {
    asyncCart(context, cart){
      context.commit('updateCart',cart);
    },
    asyncUserName(context, username){
      context.commit('updateUserName',username);
    },
    asyncAddress(context, address){
      context.commit('updateAddress',address);
    },
    asyncProductDict(context, productDict){
      context.commit('updateProductDict',productDict);
    },
  },
  modules: {
  },
})
