import Vue from 'vue'
import Vuex from 'vuex'

Vue.use(Vuex)

//存放购物车数据的全局变量，以保证在反复跳转后，订单信息不会丢失
//Vue.prototype.$cart = [];

export default new Vuex.Store({
      state: {
            cart: new Map(),
            username: "user1",
            address: "我是收货地址",
            userid: 1,
            favorite : [],
            productDict: new Map([  //产品的信息表
                  //BISAGRA 4''
                  ['4-AB', "BISAGRA 4''"],
                  ['4-AC', "BISAGRA 4''"],
                  ['4-SN', "BISAGRA 4''"],
                  //SUJETADOR
                  ['CLIC-1', 'SUJETADOR'],
                  ['SUJ-1', 'SUJETADOR'],
                  ['SUJ-2', 'SUJETADOR'],
                  ['SUJ-3', 'SUJETADOR'],
                  //TORNILLO
                  ['TORNILLO A', 'TORNILLO'],
                  ['TORNILLO N', 'TORNILLO'],
                  ['TORNILLO T2', 'TORNILLO'],
                  ['TORNILLO T2-1', 'TORNILLO'],
                  ['TORNILLO A-1000', 'TORNILLO'],
                  ['T2-T', 'TORNILLO'],
                  ['T2-TB', 'TORNILLO'],
                  ['T2-TB-L', 'TORNILLO'],
                  ['T2-TC-L', 'TORNILLO'],
                  ['T2-T-L', 'TORNILLO'],
                  //SILICONA
                  ['High Grab-118', 'SILICONA'],
                  ['High Grab-116', 'SILICONA'],
                  ['HT-N', 'SILICONA'],
                  ['HT-C', 'SILICONA'],
                  //OMEGA
                  ['OMEGA-3 (0,45)', 'OMEGA'],
                  //ANGULO
                  ['ANGULO-3 (0,45)', 'ANGULO'],
                  ['ANGULO-3 (35-0.45)', 'ANGULO'],
                  ['CONERBEAD-3 (0,45)', 'ANGULO'],
                  //MONTANTE
                  ['MONTANTE-3 (0,45)', 'MONTANTE'],
                  ['MONTANTE-3 (0,35)', 'MONTANTE'],
                  ['MONTANTE-64', 'MONTANTE'],
                  ['MONTANTE-70', 'MONTANTE'],
                  ['MONTANTE-64 SS', 'MONTANTE'],
                  //PERFILERIA ACUSTICA TRANSVERSAL1.2
                  ['PAT-1200', 'PERFILERIA ACUSTICA TRANSVERSAL1.2'],
                  //PERFILERIA ACUSTICA TRANSVERSAL0.6
                  ['PAT-600', 'PERFILERIA ACUSTICA TRANSVERSAL0.6'],
                  //PERFILERIA ACUSTICA PERIMETRAL
                  ['PAP-3000', 'PERFILERIA ACUSTICA PERIMETRAL'],
                  //CENTRAL ACOUSTIC PROFILERY
                  ['PAC-3600', 'CENTRAL ACOUSTIC PROFILERY'],
                  ['PAC-3600N', 'CENTRAL ACOUSTIC PROFILERY'],
                  //SOLERA
                  ['SOLERA-65', 'SOLERA'],
                  ['SOLERA-72', 'SOLERA'],
                  ['SOLERA-3 (0,45)', 'SOLERA'],
                  ['SOLERA-3 (0,35)', 'SOLERA'],
                  //Buña Z
                  ['Buña Z-2,4m(0,4)', 'Buña Z'],
                  //PISO FLOTANTE SPC
                  ['PF01C', 'PISO FLOTANTE SPC'],
                  ['PF02', 'PISO FLOTANTE SPC'],
                  ['PF02C', 'PISO FLOTANTE SPC'],
                  ['PF03', 'PISO FLOTANTE SPC'],
                  ['PF03C', 'PISO FLOTANTE SPC'],
                  ['PF04', 'PISO FLOTANTE SPC'],
                  ['PF04C', 'PISO FLOTANTE SPC'],
                  ['PF05', 'PISO FLOTANTE SPC'],
                  ['PF05C', 'PISO FLOTANTE SPC'],
                  ['PF06C', 'PISO FLOTANTE SPC'],
                  ['PF07C', 'PISO FLOTANTE SPC'],
                  ['PF08C', 'PISO FLOTANTE SPC'],
                  ['PF09C', 'PISO FLOTANTE SPC'],
                  ['PF09 SPC', 'PISO FLOTANTE SPC'],
                  ['PF10', 'PISO FLOTANTE SPC'],
                  ['PF10C', 'PISO FLOTANTE SPC'],
                  ['PF11C', 'PISO FLOTANTE SPC'],
                  ['PF11 SPC', 'PISO FLOTANTE SPC'],
                  ['PF12C', 'PISO FLOTANTE SPC'],
                  ['PF12 SPC', 'PISO FLOTANTE SPC'],
                  ['PF13', 'PISO FLOTANTE SPC'],
                  ['PF14', 'PISO FLOTANTE SPC'],
                  ['PF15', 'PISO FLOTANTE SPC'],
                  ['PF16', 'PISO FLOTANTE SPC'],
                  ['PF17', 'PISO FLOTANTE SPC'],
                  ['PF18', 'PISO FLOTANTE SPC'],
                  ['PF19', 'PISO FLOTANTE SPC'],
                  ['PF20', 'PISO FLOTANTE SPC'],
                  ['PF21', 'PISO FLOTANTE SPC'],
                  ['PF22', 'PISO FLOTANTE SPC'],
                  ['PF23', 'PISO FLOTANTE SPC'],
                  //PISO ADHESIVO
                  ['M-1209', 'PISO ADHESIVO'],
                  ['M-1212', 'PISO ADHESIVO'],
                  ['M-8123', 'PISO ADHESIVO'],
                  ['M-8129', 'PISO ADHESIVO'],
                  ['M-8806', 'PISO ADHESIVO'],
                  ['M-8809', 'PISO ADHESIVO'],
                  //	ALFOMBRA AUTOADHESIVA
                  ['AP-1', 'ALFOMBRA AUTOADHESIVA'],
                  ['AP-2', 'ALFOMBRA AUTOADHESIVA'],
                  ['AP-3', 'ALFOMBRA AUTOADHESIVA'],
                  ['AP-4', 'ALFOMBRA AUTOADHESIVA'],
                  ['AP-5', 'ALFOMBRA AUTOADHESIVA'],
                  //GYPSUM 595
                  ['GS-154', 'GYPSUM 595'],
                  ['GS-238', 'GYPSUM 595'],
                  ['GS-975', 'GYPSUM 595'],
                  ['GS-996', 'GYPSUM 595'],
                  ['GS-2034-1', 'GYPSUM 595'],
                  ['GS-2034-2', 'GYPSUM 595'],
                  //PLACA DE PVC
                  ['BV595-0', 'PLACA DE PVC'],
                  ['BV595-1', 'PLACA DE PVC'],
                  ['BV595-2', 'PLACA DE PVC'],
                  ['BV595-3', 'PLACA DE PVC'],
                  ['BV595-4', 'PLACA DE PVC'],
                  ['BV595-5', 'PLACA DE PVC'],
                  ['BV595-6', 'PLACA DE PVC'],
                  ['BV595-7', 'PLACA DE PVC'],
                  ['BV595-8', 'PLACA DE PVC'],
                  ['BV595-9', 'PLACA DE PVC'],
                  ['BV595-10', 'PLACA DE PVC'],
                  ['BV595-11', 'PLACA DE PVC'],
                  ['BV595-12', 'PLACA DE PVC'],
                  ['BV595-13', 'PLACA DE PVC'],
                  //CIELO FALSO PVC ANCHO 20CM
                  ['BV200-B', 'CIELO FALSO PVC ANCHO 20CM'],
                  ['BV200-B10', 'CIELO FALSO PVC ANCHO 20CM'],
                  ['BV200-E10', 'CIELO FALSO PVC ANCHO 20CM'],
                  //CIELO FALSO PVC ANCHO 25CM
                  ['BV202-25', 'CIELO FALSO PVC ANCHO 25CM'],
                  ['BV250-B1', 'CIELO FALSO PVC ANCHO 25CM'],
                  ['BV250-B2', 'CIELO FALSO PVC ANCHO 25CM'],
                  ['BV250-M2', 'CIELO FALSO PVC ANCHO 25CM'],
                  ['BV2500', 'CIELO FALSO PVC ANCHO 25CM'],
                  ['BV2501', 'CIELO FALSO PVC ANCHO 25CM'],
                  ['BV2502', 'CIELO FALSO PVC ANCHO 25CM'],
                  ['BV2503', 'CIELO FALSO PVC ANCHO 25CM'],
                  ['BV2504', 'CIELO FALSO PVC ANCHO 25CM'],
                  ['BV2505', 'CIELO FALSO PVC ANCHO 25CM'],
                  ['BV2506', 'CIELO FALSO PVC ANCHO 25CM'],
                  ['BV251', 'CIELO FALSO PVC ANCHO 25CM'],
                  ['BV2510', 'CIELO FALSO PVC ANCHO 25CM'],
                  ['BV2512', 'CIELO FALSO PVC ANCHO 25CM'],
                  ['BV2513', 'CIELO FALSO PVC ANCHO 25CM'],
                  ['BV2514', 'CIELO FALSO PVC ANCHO 25CM'],
                  ['BV2515', 'CIELO FALSO PVC ANCHO 25CM'],
                  ['BV2517', 'CIELO FALSO PVC ANCHO 25CM'],
                  ['BV252', 'CIELO FALSO PVC ANCHO 25CM'],
                  ['BV2522', 'CIELO FALSO PVC ANCHO 25CM'],
                  ['BV2522-6', 'CIELO FALSO PVC ANCHO 25CM'],
                  ['BV2524', 'CIELO FALSO PVC ANCHO 25CM'],
                  ['BV2525', 'CIELO FALSO PVC ANCHO 25CM'],
                  ['BV2526', 'CIELO FALSO PVC ANCHO 25CM'],
                  ['BV2527', 'CIELO FALSO PVC ANCHO 25CM'],
                  ['BV2528', 'CIELO FALSO PVC ANCHO 25CM'],
                  ['BV2529', 'CIELO FALSO PVC ANCHO 25CM'],
                  ['BV253', 'CIELO FALSO PVC ANCHO 25CM'],
                  ['BV253-5M', 'CIELO FALSO PVC ANCHO 25CM'],
                  ['BV253-H', 'CIELO FALSO PVC ANCHO 25CM'],
                  ['BV2531', 'CIELO FALSO PVC ANCHO 25CM'],
                  ['BV2531-6', 'CIELO FALSO PVC ANCHO 25CM'],
                  ['BV2532', 'CIELO FALSO PVC ANCHO 25CM'],
                  ['BV2536', 'CIELO FALSO PVC ANCHO 25CM'],
                  ['BV2538', 'CIELO FALSO PVC ANCHO 25CM'],
                  ['BV254', 'CIELO FALSO PVC ANCHO 25CM'],
                  ['BV254-A', 'CIELO FALSO PVC ANCHO 25CM'],
                  ['BV254-H', 'CIELO FALSO PVC ANCHO 25CM'],
                  ['BV2541', 'CIELO FALSO PVC ANCHO 25CM'],
                  ['BV2543', 'CIELO FALSO PVC ANCHO 25CM'],
                  ['BV2545', 'CIELO FALSO PVC ANCHO 25CM'],
                  ['BV2548', 'CIELO FALSO PVC ANCHO 25CM'],
                  ['BV2548-6', 'CIELO FALSO PVC ANCHO 25CM'],
                  ['BV255', 'CIELO FALSO PVC ANCHO 25CM'],
                  ['BV255-A', 'CIELO FALSO PVC ANCHO 25CM'],
                  ['BV255-H', 'CIELO FALSO PVC ANCHO 25CM'],
                  ['BV2550', 'CIELO FALSO PVC ANCHO 25CM'],
                  ['BV2553', 'CIELO FALSO PVC ANCHO 25CM'],
                  ['BV2555', 'CIELO FALSO PVC ANCHO 25CM'],
                  ['BV2557', 'CIELO FALSO PVC ANCHO 25CM'],
                  ['BV2557-H', 'CIELO FALSO PVC ANCHO 25CM'],
                  ['BV2557N-W', 'CIELO FALSO PVC ANCHO 25CM'],
                  ['BV2557N-W-H', 'CIELO FALSO PVC ANCHO 25CM'],
                  ['BV2559', 'CIELO FALSO PVC ANCHO 25CM'],
                  ['BV256', 'CIELO FALSO PVC ANCHO 25CM'],
                  ['BV2560', 'CIELO FALSO PVC ANCHO 25CM'],
                  ['BV2561', 'CIELO FALSO PVC ANCHO 25CM'],
                  ['BV2562', 'CIELO FALSO PVC ANCHO 25CM'],
                  ['BV2563', 'CIELO FALSO PVC ANCHO 25CM'],
                  ['BV2564', 'CIELO FALSO PVC ANCHO 25CM'],
                  ['BV2565', 'CIELO FALSO PVC ANCHO 25CM'],
                  ['BV2567', 'CIELO FALSO PVC ANCHO 25CM'],
                  ['BV257', 'CIELO FALSO PVC ANCHO 25CM'],
                  ['BV2570', 'CIELO FALSO PVC ANCHO 25CM'],
                  ['BV2571', 'CIELO FALSO PVC ANCHO 25CM'],
                  ['BV2572', 'CIELO FALSO PVC ANCHO 25CM'],
                  ['BV2573-H', 'CIELO FALSO PVC ANCHO 25CM'],
                  ['BV258', 'CIELO FALSO PVC ANCHO 25CM'],
                  ['BV259', 'CIELO FALSO PVC ANCHO 25CM'],
                  ['BV2590-H', 'CIELO FALSO PVC ANCHO 25CM'],
                  ['BV2592', 'CIELO FALSO PVC ANCHO 25CM'],
                  ['BV2592-A', 'CIELO FALSO PVC ANCHO 25CM'],
                  ['BV2592-H', 'CIELO FALSO PVC ANCHO 25CM'],
                  ['BV2593', 'CIELO FALSO PVC ANCHO 25CM'],
                  ['BV2593-H', 'CIELO FALSO PVC ANCHO 25CM'],
                  ['BV2594', 'CIELO FALSO PVC ANCHO 25CM'],
                  ['BV2595', 'CIELO FALSO PVC ANCHO 25CM'],
                  ['BV2595-A', 'CIELO FALSO PVC ANCHO 25CM'],
                  ['BV2595-H', 'CIELO FALSO PVC ANCHO 25CM'],
                  ['BV2598-H', 'CIELO FALSO PVC ANCHO 25CM'],
                  ['BV2599', 'CIELO FALSO PVC ANCHO 25CM'],
                  //CIELO FALSO PVC ANCHO 30CM
                  ['BV300', 'CIELO FALSO PVC ANCHO 30CM'],
                  ['BV300-B', 'CIELO FALSO PVC ANCHO 30CM'],
                  ['BV301', 'CIELO FALSO PVC ANCHO 30CM'],
                  ['BV303', 'CIELO FALSO PVC ANCHO 30CM'],
                  ['BV350', 'CIELO FALSO PVC ANCHO 30CM'],
                  ['BV351', 'CIELO FALSO PVC ANCHO 30CM'],
                  ['BV352', 'CIELO FALSO PVC ANCHO 30CM'],
                  ['BV353', 'CIELO FALSO PVC ANCHO 30CM'],
                  ['BV354', 'CIELO FALSO PVC ANCHO 30CM'],
                  ['BV354-H', 'CIELO FALSO PVC ANCHO 30CM'],
                  ['BV355', 'CIELO FALSO PVC ANCHO 30CM'],
                  ['BV355-H', 'CIELO FALSO PVC ANCHO 30CM'],
                  ['PB300-B', 'CIELO FALSO PVC ANCHO 30CM'],
                  ['PB300M', 'CIELO FALSO PVC ANCHO 30CM'],
                  ['PB301', 'CIELO FALSO PVC ANCHO 30CM'],
                  ['PB302', 'CIELO FALSO PVC ANCHO 30CM'],
                  ['PB303', 'CIELO FALSO PVC ANCHO 30CM'],
                  ['PB305', 'CIELO FALSO PVC ANCHO 30CM'],
                  //CORNISA PVC MODELO T
                  ['T01', 'CORNISA PVC MODELO T'],
                  ['T01 MATE', 'CORNISA PVC MODELO T'],
                  ['T01-C', 'CORNISA PVC MODELO T'],
                  ['T01-K', 'CORNISA PVC MODELO T'],
                  ['T01-M', 'CORNISA PVC MODELO T'],
                  ['T01-PL', 'CORNISA PVC MODELO T'],
                  ['T10', 'CORNISA PVC MODELO T'],
                  ['T-205T', 'CORNISA PVC MODELO T'],
                  ['T-207T', 'CORNISA PVC MODELO T'],
                  ['T-208T', 'CORNISA PVC MODELO T'],
                  ['T25-07', 'CORNISA PVC MODELO T'],
                  ['T-251', 'CORNISA PVC MODELO T'],
                  ['T-251-A', 'CORNISA PVC MODELO T'],
                  ['T-253', 'CORNISA PVC MODELO T'],
                  ['T-253-H', 'CORNISA PVC MODELO T'],
                  ['T-254', 'CORNISA PVC MODELO T'],
                  ['T-254-A', 'CORNISA PVC MODELO T'],
                  ['T-254-H', 'CORNISA PVC MODELO T'],
                  ['T-255', 'CORNISA PVC MODELO T'],
                  ['T-2557', 'CORNISA PVC MODELO T'],
                  ['T-2557-A', 'CORNISA PVC MODELO T'],
                  ['T-2557-H', 'CORNISA PVC MODELO T'],
                  ['T-2557N-W', 'CORNISA PVC MODELO T'],
                  ['T-2557N-W-A', 'CORNISA PVC MODELO T'],
                  ['T-2557N-W-H', 'CORNISA PVC MODELO T'],
                  ['T-255-A', 'CORNISA PVC MODELO T'],
                  ['T-255-H', 'CORNISA PVC MODELO T'],
                  ['T-256', 'CORNISA PVC MODELO T'],
                  ['T-257', 'CORNISA PVC MODELO T'],
                  ['T-2570', 'CORNISA PVC MODELO T'],
                  ['T-2571', 'CORNISA PVC MODELO T'],
                  ['T-2572', 'CORNISA PVC MODELO T'],
                  ['T-2573', 'CORNISA PVC MODELO T'],
                  ['T-2574', 'CORNISA PVC MODELO T'],
                  ['T-258', 'CORNISA PVC MODELO T'],
                  ['T-2590-H', 'CORNISA PVC MODELO T'],
                  ['T-2592', 'CORNISA PVC MODELO T'],
                  ['T-2592-A', 'CORNISA PVC MODELO T'],
                  ['T-2592-H', 'CORNISA PVC MODELO T'],
                  ['T-2593', 'CORNISA PVC MODELO T'],
                  ['T-2593-A', 'CORNISA PVC MODELO T'],
                  ['T-2593-H', 'CORNISA PVC MODELO T'],
                  ['T-2594', 'CORNISA PVC MODELO T'],
                  ['T-2595', 'CORNISA PVC MODELO T'],
                  ['T-2595-A', 'CORNISA PVC MODELO T'],
                  ['T-2595-H', 'CORNISA PVC MODELO T'],
                  ['T-2598', 'CORNISA PVC MODELO T'],
                  ['T-2598-H', 'CORNISA PVC MODELO T'],
                  ['T-2599', 'CORNISA PVC MODELO T'],
                  ['T-2599-H', 'CORNISA PVC MODELO T'],
                  ['T-PB304', 'CORNISA PVC MODELO T'],

                  ['U01', 'CORNISA PVC MODELO U'],
                  ['U01-C', 'CORNISA PVC MODELO U'],
                  ['U01-K', 'CORNISA PVC MODELO U'],
                  ['U-207T', 'CORNISA PVC MODELO U'],
                  ['U-2504', 'CORNISA PVC MODELO U'],
                  ['U-251', 'CORNISA PVC MODELO U'],
                  ['U-251-A', 'CORNISA PVC MODELO U'],
                  ['U-253', 'CORNISA PVC MODELO U'],
                  ['U-253-H', 'CORNISA PVC MODELO U'],
                  ['U-254', 'CORNISA PVC MODELO U'],
                  ['U-254-H', 'CORNISA PVC MODELO U'],
                  ['U-254-A', 'CORNISA PVC MODELO U'],
                  ['U-254-H', 'CORNISA PVC MODELO U'],
                  ['U-255', 'CORNISA PVC MODELO U'],
                  ['U-255-H', 'CORNISA PVC MODELO U'],
                  ['U-2557', 'CORNISA PVC MODELO U'],
                  ['U-2557-A', 'CORNISA PVC MODELO U'],
                  ['U-2557N-W', 'CORNISA PVC MODELO U'],
                  ['U-2557N-W-A', 'CORNISA PVC MODELO U'],
                  ['U-2557N-W-H', 'CORNISA PVC MODELO U'],
                  ['U-255-A', 'CORNISA PVC MODELO U'],
                  ['U-2570', 'CORNISA PVC MODELO U'],
                  ['U-2571', 'CORNISA PVC MODELO U'],
                  ['U-2572', 'CORNISA PVC MODELO U'],
                  ['U-2573', 'CORNISA PVC MODELO U'],
                  ['U-2574', 'CORNISA PVC MODELO U'],
                  ['U-258', 'CORNISA PVC MODELO U'],
                  ['U-2590-H', 'CORNISA PVC MODELO U'],
                  ['U-2592-A', 'CORNISA PVC MODELO U'],
                  ['U-2593-A', 'CORNISA PVC MODELO U'],
                  ['U-2593-H', 'CORNISA PVC MODELO U'],
                  ['U-2595', 'CORNISA PVC MODELO U'],
                  ['U-2595-A', 'CORNISA PVC MODELO U'],
                  ['U-2595-H', 'CORNISA PVC MODELO U'],
                  ['UP01', 'CORNISA PVC MODELO U'],
                  //CORNISA PVC MODELO F
                  ['F01', 'CORNISA PVC MODELO F'],
                  ['F01-K', 'CORNISA PVC MODELO F'],
                  ['F-251', 'CORNISA PVC MODELO F'],
                  ['F-251 P', 'CORNISA PVC MODELO F'],
                  ['F-253', 'CORNISA PVC MODELO F'],
                  ['F-253 P', 'CORNISA PVC MODELO F'],
                  ['F-255', 'CORNISA PVC MODELO F'],
                  ['F-255 P', 'CORNISA PVC MODELO F'],
                  ['F-2557N-w', 'CORNISA PVC MODELO F'],
                  ['F-2570', 'CORNISA PVC MODELO F'],
                  ['F-2572', 'CORNISA PVC MODELO F'],
                  ['F-2573', 'CORNISA PVC MODELO F'],
                  ['F-2574', 'CORNISA PVC MODELO F'],
                  ['F-2592', 'CORNISA PVC MODELO F'],
                  ['F-2598', 'CORNISA PVC MODELO F'],
                  ['F-2599', 'CORNISA PVC MODELO F'],
                  //CORNISA PVC MODELO UA
                  ['AF-01-B', 'CORNISA PVC MODELO UA'],
                  ['AF-01-M', 'CORNISA PVC MODELO UA'],
                  ['AF-02', 'CORNISA PVC MODELO UA'],
                  ['AF-03', 'CORNISA PVC MODELO UA'],
                  ['AF-04', 'CORNISA PVC MODELO UA'],
                  ['AF-05', 'CORNISA PVC MODELO UA'],
                  ['AF-06', 'CORNISA PVC MODELO UA'],
                  ['AF-07', 'CORNISA PVC MODELO UA'],
                  ['UA-C91', 'CORNISA PVC MODELO UA'],
                  ['UA-R224', 'CORNISA PVC MODELO UA'],
                  ['UA-R585', 'CORNISA PVC MODELO UA'],
                  ['UA-R767', 'CORNISA PVC MODELO UA'],
                  ['UA-R781', 'CORNISA PVC MODELO UA'],
                  //CORNISA PVC MODELO H
                  ['H01', 'CORNISA PVC MODELO H'],
                  ['H01-C', 'CORNISA PVC MODELO H'],
                  ['H01-K', 'CORNISA PVC MODELO H'],
                  ['H10', 'CORNISA PVC MODELO H'],
                  ['H-205T', 'CORNISA PVC MODELO H'],
                  ['H-207T', 'CORNISA PVC MODELO H'],
                  ['H-251', 'CORNISA PVC MODELO H'],
                  ['H-251-A', 'CORNISA PVC MODELO H'],
                  ['H-253', 'CORNISA PVC MODELO H'],
                  ['H-254', 'CORNISA PVC MODELO H'],
                  ['H-254-A', 'CORNISA PVC MODELO H'],
                  ['H-254-H', 'CORNISA PVC MODELO H'],
                  ['H-255', 'CORNISA PVC MODELO H'],
                  ['H-2557', 'CORNISA PVC MODELO H'],
                  ['H-2557-A', 'CORNISA PVC MODELO H'],
                  ['H-2557-H', 'CORNISA PVC MODELO H'],
                  ['H-2557N-W', 'CORNISA PVC MODELO H'],
                  ['H-2557N-W-A', 'CORNISA PVC MODELO H'],
                  ['H-255-A', 'CORNISA PVC MODELO H'],
                  ['H-256', 'CORNISA PVC MODELO H'],
                  ['H-2570', 'CORNISA PVC MODELO H'],
                  ['H-2571', 'CORNISA PVC MODELO H'],
                  ['H-2572', 'CORNISA PVC MODELO H'],
                  ['H-2573', 'CORNISA PVC MODELO H'],
                  ['H-2574', 'CORNISA PVC MODELO H'],
                  ['H-258', 'CORNISA PVC MODELO H'],
                  ['H-2590-H', 'CORNISA PVC MODELO H'],
                  ['H-2592', 'CORNISA PVC MODELO H'],
                  ['H-2592-A', 'CORNISA PVC MODELO H'],
                  ['H-2592-H', 'CORNISA PVC MODELO H'],
                  ['H-2593', 'CORNISA PVC MODELO H'],
                  ['H-2593-A', 'CORNISA PVC MODELO H'],
                  ['H-2593-H', 'CORNISA PVC MODELO H'],
                  ['H-2595', 'CORNISA PVC MODELO H'],
                  ['H-2595-A', 'CORNISA PVC MODELO H'],
                  ['H-2595-H', 'CORNISA PVC MODELO H'],
                  ['H-2597-H', 'CORNISA PVC MODELO H'],
                  ['H-2598', 'CORNISA PVC MODELO H'],
                  ['H-2598-H', 'CORNISA PVC MODELO H'],
                  ['H-2599', 'CORNISA PVC MODELO H'],
                  ['H-BV615', 'CORNISA PVC MODELO H'],
                  ['HP01', 'CORNISA PVC MODELO H'],
                  ['H-PB304', 'CORNISA PVC MODELO H'],
                  //CINTA DE DRYWALL
                  ['CIN-1', 'CINTA DE DRYWALL'],
                  ['CIN-3', 'CINTA DE DRYWALL'],
                  ['CIN-7', 'CINTA DE DRYWALL'],
                  ['CIN-CONTRUTEC', 'CINTA DE DRYWALL'],
                  ['PE-6', 'CINTA DE DRYWALL'],
                  //PLACA DE YESO
                  ['PLACA-KN1', 'PLACA DE YESO'],
                  ['PLACA-KN2', 'PLACA DE YESO'],
                  ['PLACA-KN3', 'PLACA DE YESO'],
                  //MASILLA
                  ['MASILLA-S1', 'MASILLA'],
                  //AUTO ADHESIVA
                  ['59-006', 'AUTO ADHESIVA'],
                  ['69-001', 'AUTO ADHESIVA'],
                  ['8103', 'AUTO ADHESIVA'],
                  ['8104', 'AUTO ADHESIVA'],
                  ['8107', 'AUTO ADHESIVA'],
                  ['83-001', 'AUTO ADHESIVA'],
                  ['83-005', 'AUTO ADHESIVA'],
                  ['AA-A6', 'AUTO ADHESIVA'],
                  ['AA-AC6', 'AUTO ADHESIVA'],
                  ['AA-AG6', 'AUTO ADHESIVA'],
                  ['AA-AG6-1', 'AUTO ADHESIVA'],
                  ['AA-B3', 'AUTO ADHESIVA'],
                  ['AA-B6', 'AUTO ADHESIVA'],
                  ['AA-B6-1', 'AUTO ADHESIVA'],
                  ['AA-C01', 'AUTO ADHESIVA'],
                  ['AA-C02', 'AUTO ADHESIVA'],
                  ['AA-C03', 'AUTO ADHESIVA'],
                  ['AA-GJ8', 'AUTO ADHESIVA'],
                  ['AA-GV6', 'AUTO ADHESIVA'],
                  ['AA-MM6', 'AUTO ADHESIVA'],
                  ['AA-MN6', 'AUTO ADHESIVA'],
                  ['AA-N3', 'AUTO ADHESIVA'],
                  ['AA-N6-C', 'AUTO ADHESIVA'],
                  ['AA-N6-O', 'AUTO ADHESIVA'],
                  ['AA-PG6', 'AUTO ADHESIVA'],
                  ['AA-PG6-1', 'AUTO ADHESIVA'],
                  ['AA-PM6', 'AUTO ADHESIVA'],
                  ['AA-PR6', 'AUTO ADHESIVA'],
                  ['AA-PV6', 'AUTO ADHESIVA'],
                  ['AA-RC6', 'AUTO ADHESIVA'],
                  ['AA-YS8', 'AUTO ADHESIVA'],
                  ['AA-Z206', 'AUTO ADHESIVA'],
                  ['AA-Z216', 'AUTO ADHESIVA'],
                  ['AD-56', 'AUTO ADHESIVA'],
                  ['CS-001', 'AUTO ADHESIVA'],
                  ['CS-002', 'AUTO ADHESIVA'],
                  ['CS-010', 'AUTO ADHESIVA'],
                  ['CS-011', 'AUTO ADHESIVA'],
                  ['CS-014', 'AUTO ADHESIVA'],
                  ['ESTRELLA ROSA', 'AUTO ADHESIVA'],
                  ['FC-28', 'AUTO ADHESIVA'],
                  ['FC-31', 'AUTO ADHESIVA'],
                  ['FC-60', 'AUTO ADHESIVA'],
                  ['FC-60-1', 'AUTO ADHESIVA'],
                  ['FC-76', 'AUTO ADHESIVA'],
                  ['FC-88', 'AUTO ADHESIVA'],
                  ['HG-066', 'AUTO ADHESIVA'],
                  ['HG-53', 'AUTO ADHESIVA'],
                  ['HG-53-001', 'AUTO ADHESIVA'],
                  ['HG-54-001', 'AUTO ADHESIVA'],
                  ['HG-56-005', 'AUTO ADHESIVA'],
                  ['HG-57', 'AUTO ADHESIVA'],
                  ['HG-58-001', 'AUTO ADHESIVA'],
                  ['HG-58-011', 'AUTO ADHESIVA'],
                  ['HG-59', 'AUTO ADHESIVA'],
                  ['HG61', 'AUTO ADHESIVA'],
                  ['HG61-002', 'AUTO ADHESIVA'],
                  ['HG-61-010', 'AUTO ADHESIVA'],
                  ['HG61-010', 'AUTO ADHESIVA'],
                  ['HG-62-004', 'AUTO ADHESIVA'],
                  ['HG-63', 'AUTO ADHESIVA'],
                  ['HG-64-001', 'AUTO ADHESIVA'],
                  ['HG-65', 'AUTO ADHESIVA'],
                  ['HG-65-010', 'AUTO ADHESIVA'],
                  ['HG-75', 'AUTO ADHESIVA'],
                  ['HG-78', 'AUTO ADHESIVA'],
                  ['HG-78-003', 'AUTO ADHESIVA'],
                  ['HG-79', 'AUTO ADHESIVA'],
                  ['HG-80-005', 'AUTO ADHESIVA'],
                  ['HG-80-011', 'AUTO ADHESIVA'],
                  ['HG-81', 'AUTO ADHESIVA'],
                  ['HG-8106', 'AUTO ADHESIVA'],
                  ['HG-83', 'AUTO ADHESIVA'],
                  ['HG-83-001', 'AUTO ADHESIVA'],
                  ['HG-9032', 'AUTO ADHESIVA'],
                  ['HG-9087', 'AUTO ADHESIVA'],
                  ['HG-9091', 'AUTO ADHESIVA'],
                  ['HG-9092', 'AUTO ADHESIVA'],
                  ['HG-9094', 'AUTO ADHESIVA'],
                  ['HG-9097', 'AUTO ADHESIVA'],
                  ['HG-9099', 'AUTO ADHESIVA'],
                  ['HG-9103', 'AUTO ADHESIVA'],
                  ['KT-001', 'AUTO ADHESIVA'],
                  ['KT-003', 'AUTO ADHESIVA'],
                  ['KT-004', 'AUTO ADHESIVA'],
                  ['KT-004-2', 'AUTO ADHESIVA'],
                  ['KT-005', 'AUTO ADHESIVA'],
                  ['KT-007', 'AUTO ADHESIVA'],
                  ['KT-010', 'AUTO ADHESIVA'],
                  ['KT-011', 'AUTO ADHESIVA'],
                  ['KT-012', 'AUTO ADHESIVA'],
                  ['KT-014', 'AUTO ADHESIVA'],
                  ['KT-015', 'AUTO ADHESIVA'],
                  ['KT-016', 'AUTO ADHESIVA'],
                  ['KT-017', 'AUTO ADHESIVA'],
                  ['KT-018', 'AUTO ADHESIVA'],
                  ['KT-019', 'AUTO ADHESIVA'],
                  ['KT-022', 'AUTO ADHESIVA'],
                  ['KT10', 'AUTO ADHESIVA'],
                  ['KT-15', 'AUTO ADHESIVA'],
                  ['KT58-007', 'AUTO ADHESIVA'],
                  ['MW-003', 'AUTO ADHESIVA'],
                  ['MW-006', 'AUTO ADHESIVA'],
                  ['MW-007', 'AUTO ADHESIVA'],
                  ['MW-009', 'AUTO ADHESIVA'],
                  ['MW-011', 'AUTO ADHESIVA'],
                  ['MW-013', 'AUTO ADHESIVA'],
                  ['MW-03', 'AUTO ADHESIVA'],
                  ['NF-17', 'AUTO ADHESIVA'],
                  ['NF-20', 'AUTO ADHESIVA'],
                  ['NF-23', 'AUTO ADHESIVA'],
                  ['OB-04', 'AUTO ADHESIVA'],
                  ['OB-05', 'AUTO ADHESIVA'],
                  ['OB-06', 'AUTO ADHESIVA'],
                  ['QM-08', 'AUTO ADHESIVA'],
                  ['RBMB01', 'AUTO ADHESIVA'],
                  ['RBXH-01', 'AUTO ADHESIVA'],
                  ['RBXK015-01', 'AUTO ADHESIVA'],
                  ['RBXK015-02', 'AUTO ADHESIVA'],
                  ['RBXK015-03', 'AUTO ADHESIVA'],
                  ['WDRB020-03', 'AUTO ADHESIVA'],
                  ['WDRBO19-ZM04', 'AUTO ADHESIVA'],
                  ['WDRBO19-ZM041', 'AUTO ADHESIVA'],
                  ['WDRBO23-01', 'AUTO ADHESIVA'],
                  ['WDXFC001-01', 'AUTO ADHESIVA'],
                  ['ZW-002', 'AUTO ADHESIVA'],
                  ['ZW-003', 'AUTO ADHESIVA'],
                  ['ZW-006', 'AUTO ADHESIVA'],
                  ['ZW-007', 'AUTO ADHESIVA'],
                  ['ZW-010', 'AUTO ADHESIVA'],
                  ['ZW-011', 'AUTO ADHESIVA'],
                  ['ZW-013', 'AUTO ADHESIVA'],
                  ['ZW-014', 'AUTO ADHESIVA'],
                  ['ZW-016', 'AUTO ADHESIVA'],
                  ['ZW-018', 'AUTO ADHESIVA'],
                  ['ZW-020', 'AUTO ADHESIVA'],
                  ['ZW-021', 'AUTO ADHESIVA'],
                  ['ZW-022', 'AUTO ADHESIVA'],
                  ['ZW-023', 'AUTO ADHESIVA'],
                  ['ZW-024', 'AUTO ADHESIVA'],
                  ['ZW-025', 'AUTO ADHESIVA'],
                  ['ZW-031', 'AUTO ADHESIVA'],
                  ['ZW-033', 'AUTO ADHESIVA'],
                  ['ZW-034', 'AUTO ADHESIVA'],
                  ['ZW-040', 'AUTO ADHESIVA'],
                  ['ZW-043', 'AUTO ADHESIVA'],
                  ['ZW-047', 'AUTO ADHESIVA'],
                  ['ZW-048', 'AUTO ADHESIVA'],
                  ['ZW-051', 'AUTO ADHESIVA'],
                  ['ZW-054', 'AUTO ADHESIVA'],
                  ['ZW-14', 'AUTO ADHESIVA'],
                  ['ZW-15', 'AUTO ADHESIVA'],
                  ['ZW-22', 'AUTO ADHESIVA'],
                  ['ZW-24', 'AUTO ADHESIVA'],
                  ['ZW-42', 'AUTO ADHESIVA'],
                  ['ZW-43', 'AUTO ADHESIVA'],
                  ['ZW-50', 'AUTO ADHESIVA'],
                  ['ZW-54', 'AUTO ADHESIVA'],
                  ['ZWH001', 'AUTO ADHESIVA'],
                  ['ZWH006', 'AUTO ADHESIVA'],
                  ['ZWH010', 'AUTO ADHESIVA'],
                  ['ZWH020', 'AUTO ADHESIVA'],
                  ['ZWH023', 'AUTO ADHESIVA'],
                  ['ZWH026', 'AUTO ADHESIVA'],
                  ['ZWH038', 'AUTO ADHESIVA'],
                  ['ZWH049', 'AUTO ADHESIVA'],
                  ['ZWH059', 'AUTO ADHESIVA'],
                  ['ZWH062', 'AUTO ADHESIVA'],
                  ['ZWH067', 'AUTO ADHESIVA'],
                  ['ZWH076', 'AUTO ADHESIVA'],
                  ['ZWH086', 'AUTO ADHESIVA'],
                  ['ZW-KT-007', 'AUTO ADHESIVA'],
                  //LAMINA MARMOLADA AUTO ADHESIVA
                  ['6031', 'LAMINA MARMOLADA AUTO ADHESIVA'],
                  ['6156', 'LAMINA MARMOLADA AUTO ADHESIVA'],
                  ['6180-3', 'LAMINA MARMOLADA AUTO ADHESIVA'],
                  ['6191', 'LAMINA MARMOLADA AUTO ADHESIVA'],
                  ['YP103', 'LAMINA MARMOLADA AUTO ADHESIVA'],
                  ['YP104', 'LAMINA MARMOLADA AUTO ADHESIVA'],
                  ['YP108', 'LAMINA MARMOLADA AUTO ADHESIVA'],
                  ['YP-30', 'LAMINA MARMOLADA AUTO ADHESIVA'],
                  ['YP-44', 'LAMINA MARMOLADA AUTO ADHESIVA'],
                  ['YP-76', 'LAMINA MARMOLADA AUTO ADHESIVA'],
                  ['YP-95', 'LAMINA MARMOLADA AUTO ADHESIVA'],
                  //ADHESIVO EN ROLLO
                  ['JC-03', 'ADHESIVO EN ROLLO'],
                  ['JC-04', 'ADHESIVO EN ROLLO'],
                  ['JC-05', 'ADHESIVO EN ROLLO'],
                  //LAMINA 3D
                  ['D003-1', 'LAMINA 3D'],
                  ['D017', 'LAMINA 3D'],
                  ['D078', 'LAMINA 3D'],
                  ['D088', 'LAMINA 3D'],
                  ['D091', 'LAMINA 3D'],
                  ['D094', 'LAMINA 3D'],
                  ['D094-ML', 'LAMINA 3D'],
                  ['D095', 'LAMINA 3D'],
                  ['D099', 'LAMINA 3D'],
                  ['D100', 'LAMINA 3D'],
                  ['D106', 'LAMINA 3D'],
                  ['D111', 'LAMINA 3D'],
                  ['D124', 'LAMINA 3D'],
                  ['D125', 'LAMINA 3D'],
                  ['D137', 'LAMINA 3D'],
                  ['D140', 'LAMINA 3D'],
                  ['D142', 'LAMINA 3D'],
                  ['D143', 'LAMINA 3D'],
                  ['D146', 'LAMINA 3D'],
                  ['D147', 'LAMINA 3D'],
                  ['D151', 'LAMINA 3D'],
                  ['D153', 'LAMINA 3D'],
                  ['D154', 'LAMINA 3D'],
                  ['D156', 'LAMINA 3D'],
                  //PAPEL ADHESIVO
                  ['C197-1', 'PAPEL ADHESIVO'],
                  ['D001-1', 'PAPEL ADHESIVO'],
                  ['D005-1', 'PAPEL ADHESIVO'],
                  ['D010-2', 'PAPEL ADHESIVO'],
                  ['KN-001', 'PAPEL ADHESIVO'],
                  ['KN-002', 'PAPEL ADHESIVO'],
                  ['KN-003', 'PAPEL ADHESIVO'],
                  ['KN-C0008-3', 'PAPEL ADHESIVO'],
                  ['KN-C0014-2', 'PAPEL ADHESIVO'],
                  ['KN-C0019-1', 'PAPEL ADHESIVO'],
                  ['KN-C0022-1', 'PAPEL ADHESIVO'],
                  ['KN-C0024-1', 'PAPEL ADHESIVO'],
                  ['KN-C0024-2', 'PAPEL ADHESIVO'],
                  ['KN-C0024-3', 'PAPEL ADHESIVO'],
                  ['KN-C0024-4', 'PAPEL ADHESIVO'],
                  ['KN-C0026-1', 'PAPEL ADHESIVO'],
                  ['KN-C0026-2', 'PAPEL ADHESIVO'],
                  ['KN-C0026-3', 'PAPEL ADHESIVO'],
                  ['KN-C0027-1', 'PAPEL ADHESIVO'],
                  ['KN-M0004-1', 'PAPEL ADHESIVO'],
                  ['KN-M0004-2', 'PAPEL ADHESIVO'],
                  ['KN-M0007-1', 'PAPEL ADHESIVO'],
                  ['KN-M0011-1', 'PAPEL ADHESIVO'],
                  ['KN-M0011-2', 'PAPEL ADHESIVO'],
                  ['KN-M0011-3', 'PAPEL ADHESIVO'],
                  ['KN-M0011-4', 'PAPEL ADHESIVO'],
                  ['KN-M0014-1', 'PAPEL ADHESIVO'],
                  ['KN-M0018-1', 'PAPEL ADHESIVO'],
                  ['KN-M0023-1', 'PAPEL ADHESIVO'],
                  ['KN-M0023-2', 'PAPEL ADHESIVO'],
                  ['KN-M0024-1', 'PAPEL ADHESIVO'],
                  ['KN-M0025-2', 'PAPEL ADHESIVO'],
                  ['KN-M0028-2', 'PAPEL ADHESIVO'],
                  ['KN-M0029-1', 'PAPEL ADHESIVO'],
                  ['KN-M0030-4', 'PAPEL ADHESIVO'],
                  ['KN-M0038-1', 'PAPEL ADHESIVO'],
                  ['KN-M0038-3', 'PAPEL ADHESIVO'],
                  ['KN-W0001-1', 'PAPEL ADHESIVO'],
                  ['KN-W0001-2', 'PAPEL ADHESIVO'],
                  ['KN-W0001-3', 'PAPEL ADHESIVO'],
                  ['KN-W0001-4', 'PAPEL ADHESIVO'],
                  ['KN-W0002-1', 'PAPEL ADHESIVO'],
                  ['KN-W0002-2', 'PAPEL ADHESIVO'],
                  ['KN-W0003-4', 'PAPEL ADHESIVO'],
                  ['KN-W0004-3', 'PAPEL ADHESIVO'],
                  ['KN-W0009-2', 'PAPEL ADHESIVO'],
                  ['KN-W0020-1', 'PAPEL ADHESIVO'],
                  ['KN-W0028-1', 'PAPEL ADHESIVO'],
                  ['KN-W0028-3', 'PAPEL ADHESIVO'],
                  ['KN-W0031-1', 'PAPEL ADHESIVO'],
                  ['KN-W0033-4', 'PAPEL ADHESIVO'],
                  ['KN-W0034-4', 'PAPEL ADHESIVO'],
                  ['KN-W0038-2', 'PAPEL ADHESIVO'],
                  ['KN-X0033-1', 'PAPEL ADHESIVO'],
                  ['KN-X0070-1', 'PAPEL ADHESIVO'],
                  ['KN-X0182-1', 'PAPEL ADHESIVO'],
                  ['KN-X0195-3', 'PAPEL ADHESIVO'],
                  //VINILO ADHESIVO PARA VIDRIO
                  ['VAV-01', 'VINILO ADHESIVO PARA VIDRIO'],
                  ['VAV-02', 'VINILO ADHESIVO PARA VIDRIO'],
                  ['VAV-03', 'VINILO ADHESIVO PARA VIDRIO'],
                  ['VAV-04', 'VINILO ADHESIVO PARA VIDRIO'],
                  //ZOCALO AUTO ADHESIVA
                  ['ZA-01', 'TBD1'],
                  ['ZA-02', 'TBD1'],
                  //Placas de Pvc marmolados,2.44m*1.22m*3mm
                  ['BV1201', 'Placas de Pvc marmolados,2.44m*1.22m*3mm'],
                  ['BV1202', 'Placas de Pvc marmolados,2.44m*1.22m*3mm'],
                  ['BV1203', 'Placas de Pvc marmolados,2.44m*1.22m*3mm'],
                  ['BV1204', 'Placas de Pvc marmolados,2.44m*1.22m*3mm'],
                  ['BV1205', 'Placas de Pvc marmolados,2.44m*1.22m*3mm'],
                  ['BV1206', 'Placas de Pvc marmolados,2.44m*1.22m*3mm'],
                  ['BV1207', 'Placas de Pvc marmolados,2.44m*1.22m*3mm'],
                  ['BV1208', 'Placas de Pvc marmolados,2.44m*1.22m*3mm'],
                  ['BV1209', 'Placas de Pvc marmolados,2.44m*1.22m*3mm'],
                  ['BV1210', 'Placas de Pvc marmolados,2.44m*1.22m*3mm'],
                  ['BV1211', 'Placas de Pvc marmolados,2.44m*1.22m*3mm'],
                  ['BV1212', 'Placas de Pvc marmolados,2.44m*1.22m*3mm'],
                  ['BV1213', 'Placas de Pvc marmolados,2.44m*1.22m*3mm'],
                  ['BV1219', 'Placas de Pvc marmolados,2.44m*1.22m*3mm'],
                  ['BV1220', 'Placas de Pvc marmolados,2.44m*1.22m*3mm'],
                  ['BV1221', 'Placas de Pvc marmolados,2.44m*1.22m*3mm'],
                  ['BV1222', 'Placas de Pvc marmolados,2.44m*1.22m*3mm'],
                  ['BV1223', 'Placas de Pvc marmolados,2.44m*1.22m*3mm'],
                  ['BV1224', 'Placas de Pvc marmolados,2.44m*1.22m*3mm'],
                  ['BV1225', 'Placas de Pvc marmolados,2.44m*1.22m*3mm'],
                  ['BV1226', 'Placas de Pvc marmolados,2.44m*1.22m*3mm'],
                  ['BV1227', 'Placas de Pvc marmolados,2.44m*1.22m*3mm'],
                  //Revestimiento Int. PVC 40cm*9mm*2.95m
                  ['BV403', 'Revestimiento Int. PVC 40cm*9mm*2.95m'],
                  ['BV404', 'Revestimiento Int. PVC 40cm*9mm*2.95m'],
                  ['BV494', 'Revestimiento Int. PVC 40cm*9mm*2.95m'],
                  ['BV496', 'Revestimiento Int. PVC 40cm*9mm*2.95m'],
                  //Revestimiento Int. PVC 60cm*8mm*2.95m
                  ['BV601', 'Revestimiento Int. PVC 60cm*8mm*2.95m'],
                  ['BV601-H', 'Revestimiento Int. PVC 60cm*8mm*2.95m'],
                  ['BV603', 'Revestimiento Int. PVC 60cm*8mm*2.95m'],
                  ['BV604', 'Revestimiento Int. PVC 60cm*8mm*2.95m'],
                  ['BV605', 'Revestimiento Int. PVC 60cm*8mm*2.95m'],
                  ['BV606', 'Revestimiento Int. PVC 60cm*8mm*2.95m'],
                  ['BV607', 'Revestimiento Int. PVC 60cm*8mm*2.95m'],
                  ['BV608', 'Revestimiento Int. PVC 60cm*8mm*2.95m'],
                  ['BV609', 'Revestimiento Int. PVC 60cm*8mm*2.95m'],
                  ['BV610', 'Revestimiento Int. PVC 60cm*8mm*2.95m'],
                  ['BV611', 'Revestimiento Int. PVC 60cm*8mm*2.95m'],
                  ['BV612', 'Revestimiento Int. PVC 60cm*8mm*2.95m'],
                  ['BV614', 'Revestimiento Int. PVC 60cm*8mm*2.95m'],
                  ['BV615', 'Revestimiento Int. PVC 60cm*8mm*2.95m'],
                  ['BV616', 'Revestimiento Int. PVC 60cm*8mm*2.95m'],
                  ['BV617', 'Revestimiento Int. PVC 60cm*8mm*2.95m'],
                  ['BV617-H', 'Revestimiento Int. PVC 60cm*8mm*2.95m'],
                  ['BV619', 'Revestimiento Int. PVC 60cm*8mm*2.95m'],
                  ['BV620', 'Revestimiento Int. PVC 60cm*8mm*2.95m'],
                  ['BV659', 'Revestimiento Int. PVC 60cm*8mm*2.95m'],
                  ['BV659-H', 'Revestimiento Int. PVC 60cm*8mm*2.95m'],
                  //Lamina tipo espejo 2.44m*1.22m*5mm
                  ['EDE-01', 'Lamina tipo espejo 2.44m*1.22m*5mm'],
                  //Panel De Aluminio 1.22M*2.8M*7MM
                  ['NA-01', 'Panel De Aluminio 1.22M*2.8M*7MM'],
                  //Panel De Aluminio 1.22M*2.9M*7MM
                  ['NA-02', 'Panel De Aluminio 1.22M*2.9M*7MM'],
                  ['NA-04', 'Panel De Aluminio 1.22M*2.9M*7MM'],
                  ['NA-05', 'Panel De Aluminio 1.22M*2.9M*7MM'],
                  ['NA-06', 'Panel De Aluminio 1.22M*2.9M*7MM'],
                  ['NA-07', 'Panel De Aluminio 1.22M*2.9M*7MM'],
                  ['NA-08', 'Panel De Aluminio 1.22M*2.9M*7MM'],
                  ['NA-09', 'Panel De Aluminio 1.22M*2.9M*7MM'],
                  //Policarbonado solido 1220mm*2440mm*3mm
                  ['PS01', 'Policarbonado solido 1220mm*2440mm*3mm'],
                  //Roca PU 1.2m*0.6m*3cm
                  ['PUA-3-1', 'Roca PU 1.2m*0.6m*3cm'],
                  ['PUA-3-12', 'Roca PU 1.2m*0.6m*3cm'],
                  ['PUA-3-4', 'Roca PU 1.2m*0.6m*3cm'],
                  ['PUA-3-6', 'Roca PU 1.2m*0.6m*3cm'],
                  ['PUA-3-7', 'Roca PU 1.2m*0.6m*3cm'],
                  ['PUA-4-3', 'Roca PU 1.2m*0.6m*3cm'],
                  //Revestimiento Ext. 3,85m*35cm*16mm
                  ['RPE-08', 'Revestimiento Ext. 3,85m*35cm*16mm'],
                  //Revestimiento Ext. 3,85m*38cm*16mm
                  ['RPE-01', 'Revestimiento Ext. 3,85m*38cm*16mm'],
                  ['RPE-02', 'Revestimiento Ext. 3,85m*38cm*16mm'],
                  ['RPE-03', 'Revestimiento Ext. 3,85m*38cm*16mm'],
                  ['RPE-04', 'Revestimiento Ext. 3,85m*38cm*16mm'],
                  ['RPE-05', 'Revestimiento Ext. 3,85m*38cm*16mm'],
                  ['RPE-06', 'Revestimiento Ext. 3,85m*38cm*16mm'],
                  //Revestimiento Ext. 3,85m*39cm*16mm
                  ['RPE-07', 'Revestimiento Ext. 3,85m*39cm*16mm'],
                  //Tubos Divisorios de WPC
                  ['TC-01', 'Tubos Divisorios de WPC'],
                  ['TC-02', 'Tubos Divisorios de WPC'],
                  ['TC-07', 'Tubos Divisorios de WPC'],
                  ['TC-09', 'Tubos Divisorios de WPC'],
                  ['TD-01', 'Tubos Divisorios de WPC'],
                  ['TD-02', 'Tubos Divisorios de WPC'],
                  ['TD-07', 'Tubos Divisorios de WPC'],
                  ['TD-09', 'Tubos Divisorios de WPC'],
                  ['WPF-01', 'Tubos Divisorios de WPC'],
                  ['WPF-03', 'Tubos Divisorios de WPC'],
                  //Wall Panel de PVC Ripado 15cm*15mm*2.9m
                  ['WP-14', 'Wall Panel de PVC Ripado 15cm*15mm*2.9m'],
                  ['WP-15', 'Wall Panel de PVC Ripado 15cm*15mm*2.9m'],
                  //Wall Panel de PVC Ripado 16cm*16mm*2.9m
                  ['WP-11', 'Wall Panel de PVC Ripado 16cm*16mm*2.9m'],
                  ['WP-12', 'Wall Panel de PVC Ripado 16cm*16mm*2.9m'],
                  //Wall Panel de PVC Ripado 16cm*24mm*2.9m
                  ['WP-01', 'Wall Panel de PVC Ripado 16cm*24mm*2.9m'],
                  ['WP-02', 'Wall Panel de PVC Ripado 16cm*24mm*2.9m'],
                  ['WP-03', 'Wall Panel de PVC Ripado 16cm*24mm*2.9m'],
                  ['WP-04', 'Wall Panel de PVC Ripado 16cm*24mm*2.9m'],
                  ['WP-07', 'Wall Panel de PVC Ripado 16cm*24mm*2.9m'],
                  ['WP-08', 'Wall Panel de PVC Ripado 16cm*24mm*2.9m'],
                  ['WP-09', 'Wall Panel de PVC Ripado 16cm*24mm*2.9m'],
                  ['WP-10', 'Wall Panel de PVC Ripado 16cm*24mm*2.9m'],
                  ['WP-13', 'Wall Panel de PVC Ripado 16cm*24mm*2.9m'],
                  ['WP-16', 'Wall Panel de PVC Ripado 16cm*24mm*2.9m'],
                  ['WP-19', 'Wall Panel de PVC Ripado 16cm*24mm*2.9m'],
                  ['WP-20', 'Wall Panel de PVC Ripado 16cm*24mm*2.9m'],
                  ['WP-21', 'Wall Panel de PVC Ripado 16cm*24mm*2.9m'],
                  ['WP-22', 'Wall Panel de PVC Ripado 16cm*24mm*2.9m'],
                  ['WPN-01', 'Wall Panel de PVC Ripado 16cm*24mm*2.9m'],
                  //Wall Panel de PVC Ripado 20cm*16mm*2.9m
                  ['WP-24', 'Wall Panel de PVC Ripado 20cm*16mm*2.9m'],
                  ['WP-25', 'Wall Panel de PVC Ripado 20cm*16mm*2.9m'],
                  ['WP-26', 'Wall Panel de PVC Ripado 20cm*16mm*2.9m'],
                  //Wall Panel de PVC Ripado 20cm*21mm*2.9m
                  ['WP-17', 'Wall Panel de PVC Ripado 20cm*21mm*2.9m'],
                  //Wall Panel de PVC Ripado 20cm*24mm*2.9m
                  ['WP-18', 'Wall Panel de PVC Ripado 20cm*24mm*2.9m'],
                  ['WP-28', 'Wall Panel de PVC Ripado 20cm*24mm*2.9m'],
                  ['WP-29', 'Wall Panel de PVC Ripado 20cm*24mm*2.9m'],
                  //Tablero De Espuma De PVC 1.22m*2.9m*5mm
                  ['XD-0008', 'Tablero De Espuma De PVC 1.22m*2.9m*5mm'],
                  ['XD-0016', 'Tablero De Espuma De PVC 1.22m*2.9m*5mm'],
                  ['XD-0017', 'Tablero De Espuma De PVC 1.22m*2.9m*5mm'],
                  //Tablero De Espuma De PVC 1.22m*2.9m*8mm
                  ['XD-0001', 'Tablero De Espuma De PVC 1.22m*2.9m*8mm'],
                  ['XD-0012', 'Tablero De Espuma De PVC 1.22m*2.9m*8mm'],
                  ['XD-0021', 'Tablero De Espuma De PVC 1.22m*2.9m*8mm'],
            ]),
      },
      getters: {
            getCart(state) {
                  return state.cart;
            },
            getUserName(state) {
                  return state.username;
            },
            getAddress(state) {
                  return state.address;
            },
            getProductDict(state) {
                  return state.productDict;
            },
            getUserID(state){
                  return state.userid;
            },
      },
      //同步方法
      mutations: {
            updateCart(state, cart) {
                  state.cart = cart;
            },
            updateUserName(state, username) {
                  state.username = username;
            },
            updateAddress(state, address) {
                  state.address = address;
            },
            updateProductDict(state, productDict) {
                  state.productDict = productDict;
            },
            updateUserID(state, userid){
                  state.userid = userid;
            },
      },
      //异步方法
      actions: {
            asyncCart(context, cart) {
                  context.commit('updateCart', cart);
            },
            asyncUserName(context, username) {
                  context.commit('updateUserName', username);
            },
            asyncAddress(context, address) {
                  context.commit('updateAddress', address);
            },
            asyncProductDict(context, productDict) {
                  context.commit('updateProductDict', productDict);
            },
            asyncUserID(context, userid) {
                  context.commit('updateUserID', userid);
            },
      },
      modules: {
      },
})
