<template>
    <div>
        <ProductList :products="products" @viewProduct="viewProductDetail" />
    </div>
</template>

<script>
import ProductList from '@/components/ProductList.vue';

export default {
    components: {
        ProductList
    },
    data() {
        return {
            products: [
                { name: '59-006', image: 'images/The-3D/AUTO-ADHESIVA/59-006.jpg' },
                { name: '69-001', image: 'images/TBD1.jpg' },
                { name: '8103', image: 'images/The-3D/AUTO-ADHESIVA/8103.jpg' },
                { name: '8104', image: 'images/The-3D/AUTO-ADHESIVA/8104.jpg' },
                { name: '8107', image: 'images/The-3D/AUTO-ADHESIVA/8107.jpg' },
                { name: '83-001', image: 'images/TBD1.jpg' },
                { name: '83-005', image: 'images/TBD1.jpg' },
                { name: 'AA-A6', image: 'images/The-3D/AUTO-ADHESIVA/AA-A6.jpg' },
                { name: 'AA-AC6', image: 'images/The-3D/AUTO-ADHESIVA/AA-AC6.jpg' },
                { name: 'AA-AG6', image: 'images/The-3D/AUTO-ADHESIVA/AA-AG6.jpg' },
                { name: 'AA-AG6-1', image: 'images/TBD1.jpg' },
                { name: 'AA-B3', image: 'images/The-3D/AUTO-ADHESIVA/AA-B3.jpg' },
                { name: 'AA-B6', image: 'images/The-3D/AUTO-ADHESIVA/AA-B6.jpg' },
                { name: 'AA-B6-1', image: 'images/TBD1.jpg' },
                { name: 'AA-C01', image: 'images/The-3D/AUTO-ADHESIVA/AA-C01.jpg' },
                { name: 'AA-C02', image: 'images/The-3D/AUTO-ADHESIVA/AA-C02.jpg' },
                { name: 'AA-C03', image: 'images/The-3D/AUTO-ADHESIVA/AA-C03.jpg' },
                { name: 'AA-GJ8', image: 'images/TBD1.jpg' },
                { name: 'AA-GV6', image: 'images/The-3D/AUTO-ADHESIVA/AA-GV6.jpg' },
                { name: 'AA-MM6', image: 'images/The-3D/AUTO-ADHESIVA/AA-MM6.jpg' },
                { name: 'AA-MN6', image: 'images/The-3D/AUTO-ADHESIVA/AA-MN6.jpg' },
                { name: 'AA-N3', image: 'images/TBD1.jpg' },
                { name: 'AA-N6-C', image: 'images/The-3D/AUTO-ADHESIVA/AA-N6.jpg' },
                { name: 'AA-N6-O', image: 'images/The-3D/AUTO-ADHESIVA/AA-N6.jpg' },
                { name: 'AA-PG6', image: 'images/The-3D/AUTO-ADHESIVA/AA-PG6.jpg' },
                { name: 'AA-PG6-1', image: 'images/TBD1.jpg' },
                { name: 'AA-PM6', image: 'images/The-3D/AUTO-ADHESIVA/AA-PM6.jpg' },
                { name: 'AA-PR6', image: 'images/The-3D/AUTO-ADHESIVA/AA-PR6.jpg' },
                { name: 'AA-PV6', image: 'images/The-3D/AUTO-ADHESIVA/AA-PV6.jpg' },
                { name: 'AA-RC6', image: 'images/The-3D/AUTO-ADHESIVA/AA-RC6.jpg' },
                { name: 'AA-YS8', image: 'images/TBD1.jpg' },
                { name: 'AA-Z206', image: 'images/The-3D/AUTO-ADHESIVA/AA-Z206.jpg' },
                { name: 'AA-Z216', image: 'images/The-3D/AUTO-ADHESIVA/AA-Z216.jpg' },
                { name: 'AD-56', image: 'images/The-3D/AUTO-ADHESIVA/AD-56.jpg' },
                { name: 'CS-001', image: 'images/The-3D/AUTO-ADHESIVA/CS-001.jpg' },
                { name: 'CS-002', image: 'images/The-3D/AUTO-ADHESIVA/CS-002.jpg' },
                { name: 'CS-010', image: 'images/The-3D/AUTO-ADHESIVA/CS-010.jpg' },
                { name: 'CS-011', image: 'images/TBD1.jpg' },
                { name: 'CS-014', image: 'images/The-3D/AUTO-ADHESIVA/CS-014.jpg' },
                { name: 'ESTRELLA ROSA', image: 'images/The-3D/AUTO-ADHESIVA/Estrella-Rosa.jpg' },
                { name: 'FC-28', image: 'images/TBD1.jpg' },
                { name: 'FC-31', image: 'images/TBD1.jpg' },
                { name: 'FC-60', image: 'images/The-3D/AUTO-ADHESIVA/FC-60.jpg' },
                { name: 'FC-60-1', image: 'images/TBD1.jpg' },
                { name: 'FC-76', image: 'images/TBD1.jpg' },
                { name: 'FC-88', image: 'images/The-3D/AUTO-ADHESIVA/FC-88.jpg' },
                { name: 'HG-066', image: 'images/TBD1.jpg' },
                { name: 'HG-53', image: 'images/The-3D/AUTO-ADHESIVA/HG-53.jpg' },
                { name: 'HG-53-001', image: 'images/The-3D/AUTO-ADHESIVA/HG-53-001.jpg' },
                { name: 'HG-54-001', image: 'images/The-3D/AUTO-ADHESIVA/HG-54-001.jpg' },
                { name: 'HG-56-005', image: 'images/The-3D/AUTO-ADHESIVA/HG-56-005.jpg' },
                { name: 'HG-57', image: 'images/TBD1.jpg' },
                { name: 'HG-58-001', image: 'images/TBD1.jpg' },
                { name: 'HG-58-011', image: 'images/The-3D/AUTO-ADHESIVA/HG-58-011.jpg' },
                { name: 'HG-59', image: 'images/TBD1.jpg' },
                { name: 'HG61', image: 'images/TBD1.jpg' },
                { name: 'HG61-002', image: 'images/The-3D/AUTO-ADHESIVA/HG61-002.jpg' },
                { name: 'HG-61-010', image: 'images/The-3D/AUTO-ADHESIVA/HG-61-010.jpg' },
                { name: 'HG61-010', image: 'images/TBD1.jpg' },
                { name: 'HG-62-004', image: 'images/The-3D/AUTO-ADHESIVA/HG-62-004.jpg' },
                { name: 'HG-63', image: 'images/TBD1.jpg' },
                { name: 'HG-64-001', image: 'images/TBD1.jpg' },
                { name: 'HG-65', image: 'images/TBD1.jpg' },
                { name: 'HG-65-010', image: 'images/The-3D/AUTO-ADHESIVA/HG-65-010.jpg' },
                { name: 'HG-75', image: 'images/TBD1.jpg' },
                { name: 'HG-78', image: 'images/TBD1.jpg' },
                { name: 'HG-78-003', image: 'images/The-3D/AUTO-ADHESIVA/HG-78-003.jpg' },
                { name: 'HG-79', image: 'images/TBD1.jpg' },
                { name: 'HG-80-005', image: 'images/The-3D/AUTO-ADHESIVA/HG-80-005.jpg' },
                { name: 'HG-80-011', image: 'images/The-3D/AUTO-ADHESIVA/HG-80-011.jpg' },
                { name: 'HG-81', image: 'images/TBD1.jpg' },
                { name: 'HG-8106', image: 'images/The-3D/AUTO-ADHESIVA/HG-8106.jpg' },
                { name: 'HG-83', image: 'images/TBD1.jpg' },
                { name: 'HG-83-001', image: 'images/TBD1.jpg' },
                { name: 'HG-9032', image: 'images/The-3D/AUTO-ADHESIVA/HG-9032.jpg' },
                { name: 'HG-9087', image: 'images/The-3D/AUTO-ADHESIVA/HG-9087.jpg' },
                { name: 'HG-9091', image: 'images/The-3D/AUTO-ADHESIVA/HG-9091.jpg' },
                { name: 'HG-9092', image: 'images/The-3D/AUTO-ADHESIVA/HG-9092.jpg' },
                { name: 'HG-9094', image: 'images/The-3D/AUTO-ADHESIVA/HG-9094.jpg' },
                { name: 'HG-9097', image: 'images/The-3D/AUTO-ADHESIVA/HG-9097.jpg' },
                { name: 'HG-9099', image: 'images/The-3D/AUTO-ADHESIVA/HG-9099.jpg' },
                { name: 'HG-9103', image: 'images/The-3D/AUTO-ADHESIVA/HG-9103.jpg' },
                { name: 'KT-001', image: 'images/The-3D/AUTO-ADHESIVA/KT-001.jpg' },
                { name: 'KT-003', image: 'images/TBD1.jpg' },
                { name: 'KT-004', image: 'images/The-3D/AUTO-ADHESIVA/KT-004.jpg' },
                { name: 'KT-004-2', image: 'images/The-3D/AUTO-ADHESIVA/KT-004-2.jpg' },
                { name: 'KT-005', image: 'images/The-3D/AUTO-ADHESIVA/KT-005.jpg' },
                { name: 'KT-007', image: 'images/The-3D/AUTO-ADHESIVA/ZW-KT-007-KT-58-007.jpg' },
                { name: 'KT-010', image: 'images/The-3D/AUTO-ADHESIVA/KT-010.jpg' },
                { name: 'KT-011', image: 'images/The-3D/AUTO-ADHESIVA/KT-011.jpg' },
                { name: 'KT-012', image: 'images/TBD1.jpg' },
                { name: 'KT-014', image: 'images/The-3D/AUTO-ADHESIVA/KT-014.jpg' },
                { name: 'KT-015', image: 'images/TBD1.jpg' },
                { name: 'KT-016', image: 'images/The-3D/AUTO-ADHESIVA/KT-016.jpg' },
                { name: 'KT-017', image: 'images/The-3D/AUTO-ADHESIVA/KT-017.jpg' },
                { name: 'KT-018', image: 'images/The-3D/AUTO-ADHESIVA/KT-018.jpg' },
                { name: 'KT-019', image: 'images/The-3D/AUTO-ADHESIVA/KT-019.jpg' },
                { name: 'KT-022', image: 'images/The-3D/AUTO-ADHESIVA/KT-022.jpg' },
                { name: 'KT10', image: 'images/TBD1.jpg' },
                { name: 'KT-15', image: 'images/TBD1.jpg' },
                { name: 'KT58-007', image: 'images/TBD1.jpg' },
                { name: 'MW-003', image: 'images/TBD1.jpg' },
                { name: 'MW-006', image: 'images/The-3D/AUTO-ADHESIVA/MW-006.jpg' },
                { name: 'MW-007', image: 'images/TBD1.jpg' },
                { name: 'MW-009', image: 'images/The-3D/AUTO-ADHESIVA/MW-013-MW-009.jpg' },
                { name: 'MW-011', image: 'images/TBD1.jpg' },
                { name: 'MW-013', image: 'images/The-3D/AUTO-ADHESIVA/MW-013-MW-009.jpg' },
                { name: 'MW-03', image: 'images/TBD1.jpg' },
                { name: 'NF-17', image: 'images/TBD1.jpg' },
                { name: 'NF-20', image: 'images/TBD1.jpg' },
                { name: 'NF-23', image: 'images/TBD1.jpg' },
                { name: 'OB-04', image: 'images/TBD1.jpg' },
                { name: 'OB-05', image: 'images/TBD1.jpg' },
                { name: 'OB-06', image: 'images/TBD1.jpg' },
                { name: 'QM-08', image: 'images/TBD1.jpg' },
                { name: 'RBMB01', image: 'images/TBD1.jpg' },
                { name: 'RBXH-01', image: 'images/TBD1.jpg' },
                { name: 'RBXK015-01', image: 'images/TBD1.jpg' },
                { name: 'RBXK015-02', image: 'images/TBD1.jpg' },
                { name: 'RBXK015-03', image: 'images/TBD1.jpg' },
                { name: 'WDRB020-03', image: 'images/TBD1.jpg' },
                { name: 'WDRBO19-ZM04', image: 'images/TBD1.jpg' },
                { name: 'WDRBO19-ZM041', image: 'images/TBD1.jpg' },
                { name: 'WDRBO23-01', image: 'images/TBD1.jpg' },
                { name: 'WDXFC001-01', image: 'images/TBD1.jpg' },
                { name: 'ZW-002', image: 'images/The-3D/AUTO-ADHESIVA/ZW-02.jpg' },
                { name: 'ZW-003', image: 'images/The-3D/AUTO-ADHESIVA/ZW-003.jpg' },
                { name: 'ZW-006', image: 'images/TBD1.jpg' },
                { name: 'ZW-007', image: 'images/The-3D/AUTO-ADHESIVA/ZW-007.jpg' },
                { name: 'ZW-010', image: 'images/TBD1.jpg' },
                { name: 'ZW-011', image: 'images/TBD1.jpg' },
                { name: 'ZW-013', image: 'images/TBD1.jpg' },
                { name: 'ZW-014', image: 'images/TBD1.jpg' },
                { name: 'ZW-016', image: 'images/The-3D/AUTO-ADHESIVA/ZW-016.jpg' },
                { name: 'ZW-018', image: 'images/The-3D/AUTO-ADHESIVA/ZW-018.jpg' },
                { name: 'ZW-020', image: 'images/TBD1.jpg' },
                { name: 'ZW-021', image: 'images/TBD1.jpg' },
                { name: 'ZW-022', image: 'images/TBD1.jpg' },
                { name: 'ZW-023', image: 'images/The-3D/AUTO-ADHESIVA/ZW-023.jpg' },
                { name: 'ZW-024', image: 'images/TBD1.jpg' },
                { name: 'ZW-025', image: 'images/TBD1.jpg' },
                { name: 'ZW-031', image: 'images/The-3D/AUTO-ADHESIVA/ZW-031.jpg' },
                { name: 'ZW-033', image: 'images/The-3D/AUTO-ADHESIVA/ZW-033.jpg' },
                { name: 'ZW-034', image: 'images/TBD1.jpg' },
                { name: 'ZW-040', image: 'images/The-3D/AUTO-ADHESIVA/ZW-040.jpg' },
                { name: 'ZW-043', image: 'images/The-3D/AUTO-ADHESIVA/ZW-043.jpg' },
                { name: 'ZW-047', image: 'images/TBD1.jpg' },
                { name: 'ZW-048', image: 'images/TBD1.jpg' },
                { name: 'ZW-051', image: 'images/TBD1.jpg' },
                { name: 'ZW-054', image: 'images/The-3D/AUTO-ADHESIVA/ZW-054.jpg' },
                { name: 'ZW-14', image: 'images/TBD1.jpg' },
                { name: 'ZW-15', image: 'images/TBD1.jpg' },
                { name: 'ZW-22', image: 'images/The-3D/AUTO-ADHESIVA/ZW-22.jpg' },
                { name: 'ZW-24', image: 'images/The-3D/AUTO-ADHESIVA/ZW-24.jpg' },
                { name: 'ZW-42', image: 'images/The-3D/AUTO-ADHESIVA/ZW-42.jpg' },
                { name: 'ZW-43', image: 'images/TBD1.jpg' },
                { name: 'ZW-50', image: 'images/TBD1.jpg' },
                { name: 'ZW-54', image: 'images/TBD1.jpg' },
                { name: 'ZWH001', image: 'images/TBD1.jpg' },
                { name: 'ZWH006', image: 'images/TBD1.jpg' },
                { name: 'ZWH010', image: 'images/TBD1.jpg' },
                { name: 'ZWH020', image: 'images/TBD1.jpg' },
                { name: 'ZWH023', image: 'images/TBD1.jpg' },
                { name: 'ZWH026', image: 'images/TBD1.jpg' },
                { name: 'ZWH038', image: 'images/TBD1.jpg' },
                { name: 'ZWH049', image: 'images/TBD1.jpg' },
                { name: 'ZWH059', image: 'images/TBD1.jpg' },
                { name: 'ZWH062', image: 'images/TBD1.jpg' },
                { name: 'ZWH067', image: 'images/TBD1.jpg' },
                { name: 'ZWH076', image: 'images/TBD1.jpg' },
                { name: 'ZWH086', image: 'images/TBD1.jpg' },
                { name: 'ZW-KT-007', image: 'images/TBD1.jpg' },
                
                // 更多商品数据
            ]
        };
    },
    methods: {
        viewProductDetail(product) {
            console.log('查看商品详情:', product);
            // 处理查看详情逻辑
        }
    }
};
</script>

<style scoped>
/* 你的样式 */
</style>